### ISSUE TITLE
zerolog.Logger methods should be on *Logger, not value type

### ISSUE THREAD

**Issue by davecheney** [rs/zerolog#1]

**Comment by rs** [comment]
Sorry I did not see this issue. The Logger type is read-only on purpose. Do you see good reason to have those methods to be on ponters? It would imply that `New` return a ponter too and would force an allocation, even for temporarty (i.e. per request) sub-loggers you want to pass on the stack.

**Comment by nicbaz** [comment]
@davecheney could you please elaborate ? Is this for consistency reasons ? Efficiency ?

**Comment by davecheney** [comment]
Calling a method on a value type makes a copy of the reciever. This copying
has a performance overhead, but it also can break counters and lock
invariants, and can become a data race.

**Comment by rs** [comment]
Here there is no lock and most of the data in the struct are pointers. A logger is read-only and sub loggers are copies. Why would you make it a pointer? I see no good reason for it.

**Comment by dcheney-atlassian** [comment]
ok, my mistake, please close this issue.
