### ISSUE TITLE
Force timestamp generation

### ISSUE THREAD

**Issue by VojtechVitek** [rs/zerolog#101]
Hi,
is there any way to force zerolog to generate a timestamps on each `.Msg()` call, if no explicit `.Timestamp()` was provided?

I understand zerolog omits default timestamps because of performance .. but I wonder if there's any way to force it.

**Comment by rs** [comment]
You just put it in the context:

```go
log = log.With().Timestamp().Logger()
```

The global logger has timestamp by default BTW.

**Comment by VojtechVitek** [comment]
Thanks for the explanation.

I accidentally removed the timestamp from the global logger myself. Ooops.

```diff
- log.Logger = zerolog.New(os.Stdout)
+ log.Logger = zerolog.New(os.Stdout).With().Timestamp().Logger()
```

Cheers!
