### ISSUE TITLE
Add `IDFromCtx` to extract request id from context directly in hlog.

### ISSUE THREAD

**Issue by huangjunwen** [rs/zerolog#103]
Currently there is only [`IDFromRequest`](https://godoc.org/github.com/rs/zerolog/hlog#IDFromRequest) in [`hlog`](https://godoc.org/github.com/rs/zerolog/hlog) package.  But sometimes the http request is absent but the request id is still useful. For example:

```
func someHandler(w http.ResponseWriter, r *http.Request) {
    // ...
    DoSomeRPC(r.Context(), input)
    // ...
}

func DoSomeRPC(ctx context.Context, input interface{}) error {
    // reqID, ok := IDFromCtx(ctx)
    // pass the reqID alone with the rpc request so that we can track the whole call chain
}
```

**Comment by rs** [comment]
Good point. Would you like to send a PR with this added function?

**Comment by huangjunwen** [comment]
Hi, here it is.
