### ISSUE TITLE
change writer in the hook

### ISSUE THREAD

**Issue by yungsem** [rs/zerolog#107]
1. will it be possible if I change the writer in the hook? like this:
```go
func (h LogHook) Run(e *zerolog.Event, level zerolog.Level, msg string) {
	if level == zerolog.ErrorLevel {
		// write to error.log
	} else {
              // write to info.log
       }
}
```
2. how can I get the output string in the hook? like this:
```go
func (h LogHook) Run(e *zerolog.Event, level zerolog.Level, msg string) {
	str := someFunction(e)
}
```

**Comment by rs** [comment]
Why don’t you use the `LevelWriter` for this?

**Comment by yungsem** [comment]
Thanks for your remind, I have my problems solved through `LevelWriter`. Please close this issue.
