### ISSUE TITLE
The order of fields from `Context` are different from the order they are added

### ISSUE THREAD

**Issue by ichitera** [rs/zerolog#109]
Hello.

I want to ask whether fields from `Context` are placed in the order they are added.

Currently, some fields from `Context` are added before the fields from `Context.Logger`, but some of the other fields are added after the fields from `Context.Logger` in JSON logs.

I think that the behavior commented at #50: "Fields from the context are added first then anything added after." is better than the current behavior because we can specify the order of the fields. Also, I think it is more readable that the contextual fields are not separately placed.

Cannot the order of fields be specified any longer?

**A Code Example:**
```go
package main

import (
	"os"

	"github.com/rs/zerolog"
)

func main() {
	zerolog.TimeFieldFormat = ""
	logger := zerolog.New(os.Stdout).With().
		Timestamp().
		Str("parent", "foo").
		Logger()

	logger.Log().Str("child", "bar").Msg("")
}

// # Output
// ## Current Behavior
//
// {"parent":"foo","child":"bar","time":1537969775}
//  ^^^^^^^^^^^^^^ ~~~~~~~~~~~~~ ^^^^^^^^^^^^^^^^^^
//  Context's      Logger's       Context's
//  Fields         Fields         Fields
//
// ## Expected Behavior
//
// {"time":1537969775,"parent":"foo","child":"bar"}
//  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ~~~~~~~~~~~~~
//  Context's                        Logger's
//  Fields                           Fields

```

**Comment by smyrman** [comment]
The `Timestamp()` is not a static field, but a _hook_ that adds the current timestamp when an event is logged. I suspect _hooks_ are _not added in order_ for performance reasons.

**Comment by rs** [comment]
That's right, hooks are executed when you call `Msg()` and thus appended at the end of the message.

**Comment by ichitera** [comment]
Thank you @smyrman and @rs.
I understand why `Timestamp()` is added at the end of the message.

So, if we want to put timestamp at the first of the message, we cannot use `Context` because the other fields of `Context` are added before the timestamp.  Is that right?

How about providing lazy evaluation fields to keep the order in which they are added, which is like [zap.Stringer](https://godoc.org/go.uber.org/zap#Stringer)? If such fields are provided, we can specify the order of fields also when we use `Context`.

e.g.

```go
package main

import (
	"os"
	"time"

	"github.com/rs/zerolog"
)

// this implements fmt.Stringer
type StringerFunc func() string

func (f StringerFunc) String() string {
	return f()
}

func main() {
	logger := zerolog.New(os.Stdout).With().
		// the value of Stringer (fmt.Stringer) is evaluated
		// when Msg() is called
		Stringer(zelolog.TimestampFieldName,
			StringerFunc(func() string {
				return time.Now().String()
			})).
		Str("parent", "foo").
		Logger()

	logger.Log().Str("child", "bar").Msg("")
}

// # Intended  Output
//
// {"time":"2006-01-02 15:04:05.999999999 -0700 MST","parent":"foo","child":"bar"}
//  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ~~~~~~~~~~~~~
//  Context's                                                       Logger's
//  Fields                                                          Fields
```

**Comment by rs** [comment]
That's not really possible with current design. The context is pre-generated and stored in the logger a `[]byte` ready to be used, so we never allocate or recompute its content. Having some dynamic part in the middle would make it a lot more complex.

**Comment by ichitera** [comment]
Thank you for the quick reply and clear explanation.
I use `Event.Timestamp` directly when I need to keep the order.

I close this issue because my question was solved.
Thank you @rs and @smyrman.
