### ISSUE TITLE
TimeFormat doesn't work with sub-second precision

### ISSUE THREAD

**Issue by eklitzke** [rs/zerolog#114]
I can't get formatted timestamps with millisecond precision using a console logger. I'm using zerolog v1.10.1, which is currently the same as master.

Here's a program demonstrating the issue:
```go
package main

import (
	"os"

	"github.com/rs/zerolog"
)

func main() {
	output := zerolog.ConsoleWriter{Out: os.Stdout, TimeFormat: "15:04:05.000"}
	log := zerolog.New(output).With().Timestamp().Logger()
	formattedTime := zerolog.TimestampFunc().Format(output.TimeFormat)
	log.Info().Str("formatted_time", formattedTime).Msg("Hello World")
}
```

When I run it:
```
$ go run demo.go 
15:52:42.000 INF Hello World formatted_time=15:52:42.441
```

The output in the console logger always prints a .000 suffix in the special timestamp field, even though `zerolog.TimestampFunc().Format(output.TimeFormat)` correctly formats the time.

**Comment by IngmarStein** [comment]
The precision is lost because the console writer parses a timestamp which had previously been formatted using the library's default timestamp format (`time.RFC3339`).
You can work around this by setting `zerolog.TimeFieldFormat = time.RFC3339Nano`.

**Comment by amery** [comment]
any plan on actually fixing this so ConsoleWriter.TimeFormat = time.RFC3339Nano works without having to override global zerolog values?

**Comment by ethrgeist** [comment]
I've just hit the exact same problem using a format like `2006-01-02T15:04:05.000-0700` works only when overriding the global zerolog `zerolog.TimeFieldFormat = time.RFC3339Nano`

Maybe atleast mention the need to override the format in a second place on https://pkg.go.dev/github.com/rs/zerolog#ConsoleWriter?
