### ISSUE TITLE
[Feature Request] Allow log level to be outputted as multiple fields with different names

### ISSUE THREAD

**Issue by JorritSalverda** [rs/zerolog#12]
Currently the default field name for the log level is `level` as respected by most logging systems. Unfortunately **Stackdriver Logging** doesn't recognize this; it only respects field name `severity` instead.

Luckily I can set this with the `LevelFieldName`:

```
// log as severity for stackdriver logging to recognize the level
zerolog.LevelFieldName = "severity"
```

However in that case I loose the `level` field as recognized by many other systems. Is it possible to be able to set multiple level field names and have the information outputted redundantly?

Or is it possible to do this with some kind of interceptor? Thx

**Comment by rs** [comment]
Check #25, it should let you do that.

**Comment by josegonzalez** [comment]
@rs that does, but can you make a release? Thanks!

**Comment by rs** [comment]
done
