### ISSUE TITLE
Feature proposal: Optional CallerMarshalFunc to format structured caller field

### ISSUE THREAD

**Issue by mikeyrcamp** [rs/zerolog#133]
Currently the caller field shows the full path to the file followed by a colon and line number. I'm proposing adding a `CallerMarshalFunc` in `globals.go` that allows the structured caller field to be formatted as desired.

**Current Format:**
```
{"caller":"/opt/foo/bar/github/zerolog/log_test.go:654","message":"msg"}
```

**One Customization Option**
```
{"caller":"zerolog/log_test.go:654","message":"msg"}
```

Will submit a PR shortly.

**Comment by rs** [comment]
Alternatively you can use compile flags to strip those paths in your binary: `-gcflags="all=-trimpath=$(CURDIR)" -asmflags="all=-trimpath=$(CURDIR)"`.

**Comment by mikeyrcamp** [comment]
@rs That's a good point. It would solve the case of only wanting to trim to the root path `foo/bar/bar.go`, but wouldn't let me trim to just the last leaf package `bar/bar.go`.
