### ISSUE TITLE
Misleading text about duplicate keys in JSON

### ISSUE THREAD

**Issue by vfaronov** [rs/zerolog#140]
[Zerolog documentation](https://godoc.org/github.com/rs/zerolog#hdr-Caveats) says:

> JSON accepts dup keys, the last one prevails

But the [JSON standard](https://tools.ietf.org/html/rfc8259#section-4) says:

> The names within an object SHOULD be unique.
   [...] When the names within an object are not
   unique, the behavior of software that receives such an object is
   unpredictable.  Many implementations report the last name/value pair
   only.  Other implementations report an error or fail to parse the 
   object, and some implementations report all of the name/value pairs,
   including duplicates.

Probably this is not an issue in practice, but then the docs should be rephrased along the lines of “Software accepting JSON logs will typically honor the last one”.

**Comment by rs** [comment]
Can you submit a PR?
