### ISSUE TITLE
Add a way to get current log level / whether logger is disabled

### ISSUE THREAD

**Issue by ysamlan** [rs/zerolog#142]
Fabulous library, but I can't find any way to deal with fallback logging in the event that there's no context/request logger found by `hlog.FromRequest`. The fallback returned by that method is a disabled logger in that case, but I'd like to be able to either a) fall back to a different logger or b) at least determine that the logger it's giving back is that disabled one. I can't even just check for the presence of the logger in the `context` because the `ctxKey` struct it uses for the lookup is also private :/

A simple fix on `hlog.FromRequest` would be to just add a map-style `ok` 2nd return value:

```
func FromRequest(r *http.Request) *zerolog.Logger, boolean
```

and just return that disabledLogger + false in the event there was no logger in the request context. If that's sane I'm happy to put up a PR for it... That'd be a breaking API change, I know, but seems pretty reasonable given that the failure state is dropping log statements on the floor completely, right? (Other option would just be to expose a `GetLevel` method on the loggers or some other way of checking whether I had a no-op/disabled logger, but I realize that's a bigger addition).

**Comment by wangyuehong** [comment]
I came across this issue and send a pull request to add the `GetLevel` method.
I'm using the following way as a workaround to check if the logger is disabled(default logger is info level).
`logger.Info().Enabled()`

**Comment by nullbio** [comment]
Had the same problem and GetLevel solved it for me, thank you. I suppose this issue can be closed now?
