### ISSUE TITLE
Is Go 1.12 really required now?

### ISSUE THREAD

**Issue by mikeboyle** [rs/zerolog#149]
It appears that between v1.14.0 and v1.14.1, `go 1.12` was added to `go.mod`
https://github.com/rs/zerolog/compare/v1.14.0...v1.14.1

I fully admit I could be doing this wrong, but it seems that if I want to use the latest version of zerolog, I cannot build my Go 1.11 projects anymore unless I upgrade to 1.12.

I'm happy to do the upgrade if something in > 1.14.1 requires it, but wanted to check on that first.

**Comment by rs** [comment]
The go mod tool added this in my back. I'm not sure why.

**Comment by rs** [comment]
Removed it on master.

**Comment by mikeboyle** [comment]
Thank you!

**Comment by gilcrest** [comment]
The Go 1.12 in the go.mod file does not mean 1.12 is required. It just means that the latest changes to the go.mod file were done using Go 1.12...  It's a little misleading, but @rs this will continue to come back every time you make changes that alter the go.mod file as it gets automatically added as part of the 1.12 modules features. this line is technically above the require section, but it's still a bit confusing...

**Comment by gilcrest** [comment]
ok maybe I'm lying above, kinda... Taken from [a thread in the main go repo](https://github.com/golang/go/issues/30446)

> I think the issue is the meaning of the go directive changed, and that change was first introduced in 1.11.4 and 1.12. I believe Go 1.11.4 and higher will build a module that contains version go 1.12 without complaint, whereas earlier 1.11 versions complain with go build github.com/me/hello: module requires Go 1.12.

It seems Go 1.11.0, 1.11.1, 1.11.2 and 1.11.3 will have issues, but 1.11.4 and up should be good with this...

**Comment by rs** [comment]
Thanks for the info. I will keep it out for now and eventually let it be added in later revisions to give some time to people currently on 1.11.0-3 to upgrade.
