### ISSUE TITLE
Feature: allow fined-grained level-control through using bit encoding for levels

### ISSUE THREAD

**Issue by krilor** [rs/zerolog#162]
Could this be useful? Maybe my use-case is a bit weird, but sometimes I want to log errors, but disable warn.

How about using bits to control if the level is to be logged.
Imagine
```
00000001 - debug -> 1
00000010 - info -> 2
00000100 - warn -> 4
00001000 - error -> 8
```
Then, in the should method, one could check if that particular bit is set, not compare using less than (<).

Something like
```
if lvl & l.level == 0 || lvl & GlobalLevel() == 0 {
		return false
}
```
https://github.com/rs/zerolog/blob/master/log.go#L409

A PR that would be considered?

**Comment by rs** [comment]
If you want to log error but disable warn, why don't you set the log level to error? I don't see a use case for a bitmask.

**Comment by krilor** [comment]
Ooops. Looks like I missed a crucial thing in my initial comment: "sometimes I want to log errors **and info**, but disable warn."

If you don't think it is a good idea, then I'll close this ticket :)

**Comment by rs** [comment]
Do you have a n example use case for this?

**Comment by krilor** [comment]
Well not really. The project I have use for it atm is not on GH.

I guess it all depends on what you use the levels for, and what I'm doing is probably not common/best practice.

Closing the tickets. Thanks for replying.
