### ISSUE TITLE
broken API compatibility between 1.8 and 1.14.3

### ISSUE THREAD

**Issue by mirtchovski** [rs/zerolog#173]
we vendored 1.8 a year ago and just brought a new internal dependency that vendored 1.14.3 the other day, just to find that API compatibility is broken. The definition of the struct ConsoleWriter has changed between the two, breaking everything that does unkeyed struct initialization (the reason we do this is exactly to figure out what structs have changed between versions and to flag potential issues). 

The 1.8 version had this:

```
type ConsoleWriter struct {
	Out     io.Writer
	NoColor bool
}
```

The new version has this:

```
type ConsoleWriter struct {
	// Out is the output destination.
	Out io.Writer

	// NoColor disables the colorized output.
	NoColor bool

	// TimeFormat specifies the format for timestamp in output.
	TimeFormat string

	// PartsOrder defines the order of parts in output.
	PartsOrder []string

	FormatTimestamp     Formatter
	FormatLevel         Formatter
	FormatCaller        Formatter
	FormatMessage       Formatter
	FormatFieldName     Formatter
	FormatFieldValue    Formatter
	FormatErrFieldName  Formatter
	FormatErrFieldValue Formatter
}
```

The compiler rightfully barfs: `too few values in zerolog.ConsoleWriter literal`. 

I know this goes against "go vet"'s dogma, but it is allowed in the language and does help in some situations. I'm not suggesting zerolog moves to v2 just for this bit, but wanted to flag the error. 

Kind regards: Andrey

**Comment by rs** [comment]
This is not considered broken compat. Even the Go std lib allows itself to add fields to struct without breaking the Go 1 contract. It is the reason why it is discouraged to used unkeyed struct init.
