### ISSUE TITLE
Export timeFormatUnixMicro format

### ISSUE THREAD

**Issue by forward32** [rs/zerolog#195]
What is the reason to make both `TimeFormatUnix` and `TimeFormatUnixMs` are exported but `timeFormatUnixMicro` not?

**Comment by wphan** [comment]
Agreed, it would make sense to export `timeFormatUnixMicro` as well.

**Comment by rs** [comment]
PR welcome.

**Comment by hazim-j** [comment]
I made a PR to correct this here.

https://github.com/rs/zerolog/pull/189

**Comment by hazimj** [comment]
I made a PR to fix this here.

https://github.com/rs/zerolog/pull/189

**Comment by forward32** [comment]
@rs seems like PR was merged? Is it already in new release? Should I close this issue?

**Comment by rs** [comment]
It's in the last release yes.
