### ISSUE TITLE
Why do you need levelWriterAdapter?

### ISSUE THREAD

**Issue by kemics** [rs/zerolog#2]
Hello,

I wanted to ask, why do you need `levelWriterAdapter`, that implements `LevelWriter`, if it `WriteLevel` just calls the `Write` `io.Writer` method with no `level` usage?

And the second question, don't you think, that in `MultiLevelWriter()` function it is better to create `lwriters`  with initial length == `len(writers))`, just like this:
 `lwriters := make([]LevelWriter, len(writers))` and then add elements by index?

Thank you for your package, it is really nice

**Comment by rs** [comment]
`New` want an `io.Writer` but if the writer does also implement `LevelWriter` I use it. The `levelWriterAdapter` is used here to unify all writers and save a type assertion/condition on each write.

The `make([]T, 0, len)` with `append` is equivalent to `make([]T, len)` with index performance-wise and I prefer the style of the former.
