### ISSUE TITLE
Broken output using TimeFormatUnixMicro format

### ISSUE THREAD

**Issue by forward32** [rs/zerolog#200]
Hi @rs,

This is output in case I use `zerolog.TimeFieldFormat = zerolog.TimeFormatUnixMicro`:
```
49865900-07-13T14:30:51Z INF ...
49865900-07-13T14:31:10Z INF ...
49865900-07-25T15:09:22Z INF ...
49865900-08-18T16:52:02Z INF ...
49865900-08-23T13:36:05Z INF ...
49865900-08-29T04:58:22Z INF ...
49865900-08-29T04:59:20Z INF ...
49865900-08-29T04:59:54Z INF ...
49865900-08-29T05:00:16Z INF ...
49865900-09-05T21:54:03Z INF ...
49865900-09-05T22:00:05Z INF ...
```
Problem is under time field, it is not continuous (example log is just several seconds).

I don't have such problem with `zerolog.TimeFieldFormat = zerolog.TimeFormatUnixMicroMs`.

Logger configured like that:
```go
o := zerolog.ConsoleWriter{Out: w, TimeFormat: time.RFC3339}
l := zerolog.New(o).With().Timestamp().Caller().Logger()
```

**Comment by wphan** [comment]
i think the problem is with `time.RFC3339`, logging Unix timestamp works for me

**Comment by forward32** [comment]
@wphan still didn't get luck with Unix timestamp, my simple example:
```go
package main

import (
	"os"
	"time"

	"github.com/rs/zerolog"
)

func init() {
	zerolog.TimeFieldFormat = zerolog.TimeFormatUnixMicro
}

func main() {
	o := zerolog.ConsoleWriter{Out: os.Stderr, TimeFormat: time.UnixDate}
	l := zerolog.New(o).With().Timestamp().Caller().Logger()
	l.Info().Msgf("test")
}

 ~/logtest  ./main 
Mon Jun 30 13:23:25 UTC 49969738 INF main.go:17 > test
 ~/logtest  ./main
Sun Jul  6 21:08:34 UTC 49969738 INF main.go:17 > test
 ~/logtest  ./main
Sat Jul 12 14:18:39 UTC 49969738 INF main.go:17 > test
 ~/logtest  ./main
Wed Jul 16 10:21:44 UTC 49969738 INF main.go:17 > test
```

Is it correct example or maybe you mean something other???

**Comment by wphan** [comment]
I'm getting the same output as you with `ConsoleWriter`, I'm using this for json logs, so I'm not using `ConsoleWriter` and get unix micro timestamps fine.

Looks like the `ConsoleWriter` is broken, quick fix, i opened a PR at https://github.com/rs/zerolog/pull/206
