### ISSUE TITLE
Question: How to edit (or update) a field

### ISSUE THREAD

**Issue by rantav** [rs/zerolog#205]
Per the caveat here https://github.com/rs/zerolog#caveats simply adding the same field twice (at a child logger) would result in two fields with the same key in the final JSON output.  
I understand why and see the tradeoff.  

But - is there a way to override this e.g. with a function such as `UpdateContext` (didn't work for me, I tried) or similar? 

I understand there could be performance implications, but in some cases I'm willing to make that tradeoff. 

Is there currently a way to override/update/remove a field from a logger? 

Thank you!

**Comment by rs** [comment]
Not in the way zerolog is currently designed.

**Comment by hcmlinj** [comment]
I have similar requirement for `UpdateContext` to set something like trace id.
But there is sometimes unexpected on AWS Lambda warm start.
I can find out something like `{"level":"debug","traceId":"xxx","traceId":"xxx","traceId":"xxx"}
` in CloudWatch.

I've tried to do `log.Logger = zerolog.New(os.Stderr).With().Timestamp().Logger()` before `log.Logger.UpdateContext`.
It works to me, but I'm not sure is there any concern or side effect.

Here is my sample code, simplified from my production code.
```golang
package test

import (
	"os"
	"testing"

	"github.com/google/uuid"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

func TestUpdateContext(t *testing.T) {
	Login("Alice")
	Login("Bob")
}

func Login(userName string) {
	log.Logger = zerolog.New(os.Stderr).With().Timestamp().Logger()
	log.Logger.UpdateContext(func(c zerolog.Context) zerolog.Context {
		return c.
			Str("traceId", uuid.NewString()).
			Str("userName", userName)
	})
	log.Info().Msg("welcome")
	footprint()
}

func footprint() {
	log.Debug().Msg("I'm here")
}
``` 

```bash
$ go test -v -race

=== RUN   TestUpdateContext
{"level":"info","traceId":"bdaf3eb0-7489-4c27-8eba-6f9f1d66c238","userName":"Alice","time":"2022-11-23T22:26:52+08:00","message":"welcome"}
{"level":"debug","traceId":"bdaf3eb0-7489-4c27-8eba-6f9f1d66c238","userName":"Alice","time":"2022-11-23T22:26:52+08:00","message":"I'm here"}
{"level":"info","traceId":"c87e0100-0824-4280-a3b7-e800a82051b2","userName":"Bob","time":"2022-11-23T22:26:52+08:00","message":"welcome"}
{"level":"debug","traceId":"c87e0100-0824-4280-a3b7-e800a82051b2","userName":"Bob","time":"2022-11-23T22:26:52+08:00","message":"I'm here"}
--- PASS: TestUpdateContext (0.00s)
PASS
ok
```

**Comment by vuhoanghiep1993** [comment]
Does zerolog support edit/remove by key now?

**Comment by rs** [comment]
It does not and will probably never do.

**Comment by yhc44** [comment]
´´´
> func Login(userName string) {
> 	log.Logger = zerolog.New(os.Stderr).With().Timestamp().Logger()
> 	log.Logger.UpdateContext(func(c zerolog.Context) zerolog.Context {
> 		return c.
> 			Str("traceId", uuid.NewString()).
> 			Str("userName", userName)
> 	})
> 	log.Info().Msg("welcome")
> 	footprint()
> }
```

Why you dont use the following:

`
func Login(userName string) {
  log.Logger = zerolog.New(os.Stderr).With().Timestamp().Logger()
  sub := logger.With().Str("traceId", uuid.NewString()).Str("userName", userName).Logger()
  sub.Info().Msg("welcome")
  footprint()
}
`
