### ISSUE TITLE
[Question] Avoiding invalid json

### ISSUE THREAD

**Issue by ldelossa** [rs/zerolog#218]
Hello,

In our code base we tend to "pass" loggers to downstream code via ctx. While doing this, it's possible the downstream code appends a key which is already present due to the upstream code adding context to the passed logger. This will make zerolog produce invalid json.

Is there any defense against this? We'd like the upstream and downstream to be decoupled and not "check" if some other code path has added a duplicate key.

**Comment by borgstrom** [comment]
Duplicate keys are not strictly prohibited: https://stackoverflow.com/questions/21832701/

This caveat is already called out in the readme. See https://github.com/rs/zerolog#caveats & https://github.com/rs/zerolog/pull/41
