### ISSUE TITLE
Is there a convenient way to add all keys and their values from a map[string]interface{} as fields?

### ISSUE THREAD

**Issue by mojochao** [rs/zerolog#222]
I have a `map[string]interface{}` containing data about some failure.  Is there a convenient way to add each key/value (where value is any JSON-serializable one) from the map?  I saw that there was a `RawJSON` field, but I don't think that is what I'm looking for, unless I'm mistaken.

Many thanks in advance!

**Comment by mojochao** [comment]
Alternatively, is there a mechanism to allow me to add a slice of various Field objects, instead of having to chain them?

**Comment by alekc** [comment]
You might want to have a look at https://github.com/rs/zerolog/blob/663cbb4c84696dad870151bfb6601200422501d1/event.go#L150 @mojochao

**Comment by mojochao** [comment]
Thanks @alekc! That looks like what I need.
