### ISSUE TITLE
Logging at Fatal level without immediate exit

### ISSUE THREAD

**Issue by theckman** [rs/zerolog#237]
Hi there,
 
I wanted to see whether there was a way to log a Fatal message without the program immediately exiting, or if that's a toggleable feature we'd be willing to support?

I want to emit a Fatal event as I hit the Fatal scenario, but before I completely exit as there is some cleanup actions I need to do afterwards. This is because other things may be logged after that's hit, and I want the humans (reading the logs) to observe the change in operating state to have maximum context when dealing with a production issue.

Cheers!

**Comment by rs** [comment]
Use the `Level` method instead.

**Comment by theckman** [comment]
@rs Ah, `WithLevel`. I made the mistake of looking at `Level()` earlier. 👍

**Comment by rs** [comment]
Ah yes sorry :)
