### ISSUE TITLE
default output to stdout

### ISSUE THREAD

**Issue by stephanwesten** [rs/zerolog#250]
Hi,

I spent an hour or so debugging zerolog, so let's see if i'm wrong or there is a bug :-)

In the sample application code (without testing.T to keep it as simple as possible) below, the default output does not go to stderr, but stdout. When I debug, I do see initialization within zerolog to stderr, but the end result is not in stderr...

```
package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/rs/zerolog/log"
)


func captureStderr(f func()) (string, error) {
	var errOccurred error // in case an error occurred
	old := os.Stderr      // keep backup of the real stderr
	r, w, err := os.Pipe()
	if err != nil {
		return "", err
	}
	os.Stderr = w

	outC := make(chan string)
	// copy the output in a separate goroutine so printing can't block indefinitely
	go func() {
		var buf bytes.Buffer
		_, cpErr := io.Copy(&buf, r)
		if cpErr != nil {
			errOccurred = cpErr
		}
		outC <- buf.String()
	}()

	// calling function which stderr we are going to capture:
	f()

	// back to normal state
	err = w.Close()
	if err != nil {
		_, err = old.Write([]byte("Could not close file, error: " + err.Error()))
		if err != nil {
			errOccurred = err
		}
	}
	os.Stderr = old // restoring the real stderr
	if errOccurred != nil {
		fmt.Printf("CaptureStderr, error occurred: %v\n", err)
	}
	return <-outC, nil
}


func main() {
	stdErr, err := captureStderr(func() {
		log.Error().Msg("sw")
	})
	if err != nil {
		fmt.Println("error: " + err.Error())
	}
	if !strings.Contains(stdErr, "sw") {
		fmt.Println("stderr does not contain, output: " + stdErr)
	} else {
		fmt.Println("ok, stderr contains: " + stdErr)
	}
}
```

```
module "awesomeProject"

go 1.14

require (
    github.com/rs/zerolog v1.19.0
)
```

**Comment by rs** [comment]
I'm not sure to follow what you are trying to do. Changing the value of os.Stderr "capture stderr". If something was initialized with os.Stderr before you changed it, it will keep the old reference.

**Comment by stephanwesten** [comment]
Sorry this was not clear.

You would expect that this very basic application would send the output of `log.Error().Msg("sw")` to stderr. This is what the documentation says. (and I could find the stderr init in zerolog code base)

However when I run this application it fails. See https://play.golang.org/p/LqTnK_A-h9G

The captured output of stderr is empty. If i change stderr with stdout in `captureStderr`, the application succeeds.

So this makes me believe that zerolog sends it output to stdout....

hth,

Stephan

**Comment by rs** [comment]
Why don’t you just print one log with zerolog from a binary on you machin and check which file handle is used? The play.golang.org certainly has stderr and stdout configured differently.

Zerolog global logger sends output to stderr by default.

**Comment by stephanwesten** [comment]
I think you miss the point, the captureStderr function (obviously) captures all output to stderr. This is independent of the play.golang.org implementation.

The goal i'm trying to achieve is to write an automated test. Note that with glog this was straightforward using captureStderr. I cannot get the same test working with zerolog...

In the zerolog code base I looked for a test that verifies that default output indeed goes to stderr. I was not able to find such a test. Could you give me a pointer?

**Comment by rs** [comment]
```
package main

import "github.com/rs/zerolog/log"

func main() {
	log.Print("test")
}
```

```
go run main.go 2> >(sed 's/^/stderr: /') > >(sed 's/^/stdout: /')
stderr: {"level":"debug","time":"2020-07-14T13:39:31+02:00","message":"test"}
```

**Comment by rs** [comment]
Don't try to capture stderr, just create a logger that outputs to you pipe or to a buffer and read that buffer in your test.

**Comment by stephanwesten** [comment]
thanks for the help.

I found the cause; zerolog initializes global variable Logger with stderr. The captureStderr() is 'too late' to redirect to another buffer. Singletons and testing, always a bad mix.

**Comment by rs** [comment]
Please check my first comment:

> If something was initialized with os.Stderr before you changed it, it will keep the old reference.

**Comment by stephanwesten** [comment]
Your comment is definitely true. I did not realize that “something” == Logger ;-)

BTW i just realized that you could add the test that verifies if default logger goes to stderr. Just re-init logger within the capture closure (this is my temp solution before moving on to separate loggers) but i get the impression that you are not that fond of captureStderr. I’m fine either way. Again, thanks for your time.
