### ISSUE TITLE
It looks like SyslogWriter does not match the syslog.Writer struct.

### ISSUE THREAD

**Issue by mangup** [rs/zerolog#260]
Zerolog:
// SyslogWriter is an interface matching a syslog.Writer struct.
type SyslogWriter interface {
	io.Writer
	Debug(m string) error
	Info(m string) error
	Warning(m string) error
	Err(m string) error
	Emerg(m string) error
	Crit(m string) error
}

Syslog:
// A Writer is a connection to a syslog server.
type Writer struct {
	priority Priority
	tag      string
	hostname string
	network  string
	raddr    string

	mu   sync.Mutex // guards conn
	conn serverConn
}

or I am wrong?

**Comment by rs** [comment]
From https://golang.org/pkg/log/syslog/ :

```
type Writer
    func Dial(network, raddr string, priority Priority, tag string) (*Writer, error)
    func New(priority Priority, tag string) (*Writer, error)
    func (w *Writer) Alert(m string) error
    func (w *Writer) Close() error
    func (w *Writer) Crit(m string) error
    func (w *Writer) Debug(m string) error
    func (w *Writer) Emerg(m string) error
    func (w *Writer) Err(m string) error
    func (w *Writer) Info(m string) error
    func (w *Writer) Notice(m string) error
    func (w *Writer) Warning(m string) error
    func (w *Writer) Write(b []byte) (int, error)
```
