### ISSUE TITLE
Make event hooks more functional

### ISSUE THREAD

**Issue by YohanBob** [rs/zerolog#264]
Hooks are seemingly supposed to allow for event filtering. However there is almost no information available which can be used to decide whether the event should be dropped. 
```go
func myhook(e *zerolog.Event, level zerolog.Level, msg string) {
    if condition { // What condition?
        e.Discard()
    }
}
```
For instance, if I were to temporarily mute everything coming from all the sources except for some predefined one, how would I achieve this? Even if each event had custom 'source' field, there would be no way to retrieve it from within the hook.

**Comment by rs** [comment]
Zerolog is focused on performance. Storing event fields would imply allocation and work against that principle.

**Comment by YohanBob** [comment]
> Zerolog is focused on performance. Storing event fields would imply allocation and work against that principle.

That is understood. But maybe there is some smart way of achieving that without allocations?

**Comment by rs** [comment]
How?
