### ISSUE TITLE
Pass zerolog json as-is to a different logger instance

### ISSUE THREAD

**Issue by fahman** [rs/zerolog#270]
I am receiving zerolog output (json) from a remote source.
I would like to pass the received zerolog output as-is to a local instance of logger so that it can log the remote json.

Up to now I have considered 
- using Hook - does not work since I cannot modify Event
- using RawJSON - does not work since it appends field to the existing event
- finding Marshaller that would marshall json output into an event - could not find such a marshaller and I am not sure if I can simply replace Event in the func(Hook) Run(e *zerolog.Event,...)

Any advice is highly appreciated

**Comment by rs** [comment]
You can use a `io.MultiWriter` or any custom writer.

**Comment by fahman** [comment]
@rs Thank you, this actually helped!

For those who might discover this question, this is what worked for me IF your aim is just to output zerolog output received from somewhere as json (in a overly simplified and dirty form):
1. You receive output of zerolog log as json from somewhere
2. You configure own writer like this:
```
type LogWriter struct {
	io.Writer
}

type msg struct {
	Message string
}

func(LogWriter) Write(p []byte) (n int, err error) {
	dec := json.NewDecoder(bytes.NewReader(p))
	var theMsg msg
	_ = dec.Decode(&theMsg)
	return os.Stderr.WriteString(theMsg.Message + "\n")
}
```
3. You configure sub-logger to use the writer like this:
```
logger := log.With().Logger().Output(LogWriter{})
```
4. You log the raw json zerolog output as message  with logger created above:
```
msg := fmt.Sprintf("{\"somekey\":{\"id\":\"123\"},\"tick\":%d,\"time\":\"2020-11-09T12:05:19+01:00\",\"message\":\"some msg\"}", 10)
logger.Log().Msg(msg)
```

Message will be output to Stderr as-is
