### ISSUE TITLE
log.Fatal() does not exit

### ISSUE THREAD

**Issue by udf2457** [rs/zerolog#273]
Using zerolog:

```
package main
import (
	"filippo.io/age"
	"github.com/rs/zerolog/log"
)
func main() {
	// Simulate function input
	agePrivateKey := `# dsffgfmgjerfgv2m22`

	// Setup recipient
	key, err := age.ParseX25519Identity(agePrivateKey)
	if err != nil {
		log.Fatal().Err(err)
	}
	log.Debug().Msgf("AGE Privkey: %s",key.String())
}
```

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4d2a62]
> goroutine 1 [running]:
> filippo.io/age.(*X25519Identity).String(0x0, 0x541400, 0x0)
> 	/tmp/gopath279280641/pkg/mod/filippo.io/age@v1.0.0-beta5/x25519.go:241 +0x22
> main.main()
> 	/tmp/sandbox454298282/prog.go:17 +0x8e

Using Go log:
```
package main
import (
	"log"
	"filippo.io/age"
)
func main() {
	agePrivateKey := `# dsffgfmgjerfgv2m22`
	key, err := age.ParseX25519Identity(agePrivateKey)
	if err != nil {
		log.Fatal(err)
	}
	log.Print(key.String())
}
```

> 2009/11/10 23:00:00 malformed secret key: separator '1' at invalid position: pos=-1, len=20
> Program exited: status 1.

**Comment by rs** [comment]
You forgot to call the `Msg` or `Send` method.
