### ISSUE TITLE
Feature: Add a .Value(label, interface{}) to Event

### ISSUE THREAD

**Issue by idcmp** [rs/zerolog#274]
So often for debugging I just want `fmt.Printf("%+v",someVar)`. Lately, I just call `.Str("foo",fmt.Sprintf("%+v",foo))` but it feels so hacky (plus does all that expensive (and possibly needless) rendering. It'd be amazing to just have a `.Value`. I know there's a `Interface()` which asks me to implement `LogObjectMarshaler`, but sometimes they're not my types I'm printing.

**Comment by phuslu** [comment]
The interface should be `.Fmt("foo", "%+v", foo)`, becuase it could be implemented with 0-allocs.
Anyway, this is a deterioration in structure logging philosophy, if I am a logging author, I would not accept this change.

**Comment by idcmp** [comment]
Oh, `.Fmt()` works too - it's just a little more general purpose. Not sure why philosophy would get in the way of ergonomics here?

**Comment by rs** [comment]
`Interface` takes an `interface{}` and does not force you to implement `LogObjectMarshaler`.

**Comment by phuslu** [comment]
`.Value("foo", foo)`  -> `.Fmt("foo", "%+v", foo)` -> `.Msgf("foo=%+v", foo)`
As you see, the initial version you requires is a little equal to an printf style API, so it's not a structure style.

Yes, it may be a little helps to debugging, but currently the `Interface` method already landed.

**Comment by idcmp** [comment]
Hey @rs  - IIRC `Interface()` does JSON marshalling, so 1) "private" fields in structs won't be serialized, 2) fields with `json:"-"` tags won't be serialized, and 3) there are some types that don't marshal well (I _believe_ `sync.RWMutex`). `encoder` is a private interface, otherwise I could drop in my own replacement where `AppendInterface()` encoded to `%+v`.

**Comment by rs** [comment]
That’s what I believe most people would expect from a json logger.

**Comment by idcmp** [comment]
Hmmm. Most services I've written with zerolog do a `terminal.IsTerminal` and then `if GOOS=="windows"` wrap `os.Stderr` in `NewColorableStderr`. Lastly a `log.Logger = log.Output(zerolog.ConsoleWriter{ ....` - in production environments the tty check fails and it writes json, but I rarely use debug non-locally, a my request for a `"%+v"` is really for debugging.

**Comment by idcmp** [comment]
I no longer have this issue.
