### ISSUE TITLE
Feature suggestion: detect repeated evt.Msg calls

### ISSUE THREAD

**Issue by cvermilion** [rs/zerolog#277]
As noted in the docstrings, repeated calls of `Msg`, `Msgf`, or `Send` on the same `*Event` may have "unexpected results". Specifically, the event can end up being used in concurrent goroutines since after the first `Msg` call the `*Event` is put back in a `sync.Pool` and possibly reused. Among other potential issues, this can easily trigger Go's race condition detector in tests. Unfortunately, if you're not familiar with the details of this library, the resulting race report is not straightforward to interpret, since the race occurs later in two concurrent log statements that are themselves unproblematic. Even if you've come across this issue before, it can be tricky to track down the source because the culprit could be any log statement that occurred prior to the race, and there's no simple code search for "`Msg`/`Msg` called twice on the same log event".

Having hit this a couple of times, I thought I'd suggest adding some way to detect this bug.

One approach would be to just add a flag to `Event` that is set on write and reset on `newEvent`. Another would be adding a special log level -- `alreadyWritten`, say -- that `e.level` is set to after writing, but is reset in `newEvent`. If `e.write` is called on an `*Event` with this level, we know that we've hit the bug. This is a bit of an abuse of the level concept, but avoids adding another field to the `Event` struct. And of course adding the check at all adds a bit of overhead to every log call, and a bit of code to the library. But given that the bug can be hard to diagnose and unpredictable in consequence, it seems worth considering. 

I'd be happy to submit a PR if this sounds like a worthwhile tradeoff.

**Comment by rs** [comment]
The `Event` type is not thread safe, so it should not be used concurrently, or you are responsible for the synchronization. A flag would not solve your issue without proper synchronization, and adding thread safety to this type is not wanted.

**Comment by cvermilion** [comment]
Sorry, I should have been clearer about the error I had in mind.

Suppose you mean something like:

```go
logger := log.With().Str("foo", "bar").Logger()
logger.Info().Msg("starting")
doStuff()
logger.Info().Msg("ending")
```

but instead you write:

```go
logger := log.Info().Str("foo", "bar")
logger.Msg("starting")
doStuff()
logger.Msg("ending")
```

Of course, this is an error, but it compiles and runs (sort of, the second log line is wrong but this is easy to miss) -- except that it sets you up for thread unsafety later, because the `Event` pointer was put in the pool twice. There isn't any issue of multi-thread access in the initial code here, just two consecutive calls to `Msg` in the same goroutine. The race occurs later only if there are concurrent logging calls, but those calls don't have to be incorrect -- `newEvent` can return the same point to multiple goroutines once this error has been made.

**Comment by rs** [comment]
A flag would not protect from that either as there is no guarantee the event hasn't be pulled out of the pool for another event, which would init the flag correctly and mix and match fields and messages from different events. I don't have a good answer to detect and prevent this type of bug.

**Comment by cvermilion** [comment]
True; that occurred to me, too. I couldn't think of anything foolproof, but it seemed that if you were using the library in a way that could trigger the race, you would eventually be likely to trigger the check.

**Comment by phuslu** [comment]
replace `*Event` with `Event` among logger interfaces(use buf pool instead of event pool) then we could prevent this error by a flag. But it may not worth.

**Comment by rs** [comment]
It would also break backward compat, so it’s not really an option.
