### ISSUE TITLE
Dynamic Hooks for zerolog

### ISSUE THREAD

**Issue by hooliganlin** [rs/zerolog#290]
I'm trying to add span contexts via [apmzerolog](https://github.com/elastic/apm-agent-go/tree/master/module/apmzerolog) and to do that I'd have to add a hook. The weird thing I'm encountering is that if I started a span or some other context to be appended in my logs, I'd have to call the `Hook` method to append the context to the logger for every log event. 

The main question is zerolog suppose to only add hooks on initialization of a `Logger`? 

I created a wrapper over a `zerolog.Logger` and a method called `TraceContext` so that I can do something like:

```
logger.TraceContext(ctx).Info().Msg("successful message")
```
However, I have to attach a hook which creates a new value-based `zerolog.Logger` and then switch the semantics to return a pointer to a `zerolog.Logger` in order to chain it correctly with the other `Events` since the receiver for methods like `Info()` requires a `*zerolog.Logger`.

Example code:
```golang
// Logger wraps a zerolog.Logger as an adapter.
type Logger struct {
	underlying zerolog.Logger
}

func NewLogger(logger zerolog.Logger) *Logger {
	return &Logger{
		underlying: logger,
	}
}

// TraceContext attaches a context.Context to the underlying zerolog.Logger and attaches an apm trace hook.
func (l *Logger) TraceContext(ctx context.Context) *zerolog.Logger {
	// TODO The switching of pointer and value semantic might go against what zerolog was trying to convey,
	// but we need figure out if hooks are meant to be only initialized once vs being added dynamically
	logger := l.underlying.Hook(apmzerolog.TraceContextHook(ctx))
	return &logger
}
```

**Comment by danielbprice** [comment]
I believe that this is probably resolved now that #559 has been merged.  I am using it for Datadog.

**Comment by danielbprice** [comment]
Hi @takanuva15 

Sadly the company for which I wrote this code no longer exists, and so a bunch of the context in brain from this time is just... gone.  Here is what I found in my notes:

```
type ddTraceLoggerHook struct{}

func (d ddTraceLoggerHook) Run(e *zerolog.Event, level zerolog.Level, message string) {
        ctx := e.GetCtx()
        if ctx == nil {
                return
        }
        span, ok := tracer.SpanFromContext(ctx)
        if !ok {
                e.Bool("unified-trace-missing", true)
                return
        }
        e.Str("dd.span_id", strconv.FormatUint(span.Context().SpanID(), 10))
        e.Str("dd.trace_id", strconv.FormatUint(span.Context().TraceID(), 10))
}


// NewLogger produces a zerolog.Logger configured with our opinioned defaults
func NewLogger(globalLogLevel string) zerolog.Logger {
        zerolog.TimeFieldFormat = time.RFC3339Nano
        logger := zerolog.New(os.Stdout)
        level, err := zerolog.ParseLevel(globalLogLevel)
        if err != nil {
                logger.Fatal().Err(err)
        }
        logger = logger.Level(level)
        if isatty.IsTerminal(os.Stdout.Fd()) {
                logger = logger.Output(zerolog.ConsoleWriter{Out: os.Stdout})
        }
        logger = logger.Hook(ddTraceLoggerHook{})
        return logger
}
```

In relevant functions, our code would then do something like:
```
func (a *ApiWhatever) Whatever(ctx context.Context) error {
    logger := p.logger.With().Ctx(ctx).Logger()
    // use the logger
    ...
}
```

I'm sorry if this is incomplete, but hopefully it helps?  Based on a quick peek at the golang sdk it does seem like they still use 64 bit ID. so the strconv should work (I know that in some cases they now use 128 bit span IDs, so, YMMV).   (https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.72.2/ddtrace#SpanContext).

**Comment by takanuva15** [comment]
@danielbprice just wanted to follow up on this - I talked to the DataDog team and [integrated](https://github.com/DataDog/dd-trace-go/pull/4370) your zerolog hook code into their dd-trace-go library after some cleanup. As of [v2.7.0](https://github.com/DataDog/dd-trace-go/releases/tag/v2.7.0), Datadog now automatically adds traces to zerolog events as long as you provide the context. Thank you for sharing your original code!

**Comment by danielbprice** [comment]
@takanuva15 that's some pretty heroic work you did-- looks challenging.  It's very kind of you to close the loop-- it's nice to know that something I did is getting used somewhere out there.
