### ISSUE TITLE
Customizing error field

### ISSUE THREAD

**Issue by atombender** [rs/zerolog#308]
We log to Kibana, which has its own standard schema, [Elastic Common Schema](https://www.elastic.co/guide/en/ecs/current/ecs-error.html) for representing errors, which typically looks like this:

```json
{
  "error": {
    "code": "dingdingding",
    "message": "Thing went dingdingding",
    "type": "TooMuchDing"
  }
}
```

Because this is indexed in a particular way, and Kibana will literally discard log messages that don't conform to this schema, we had to change the Zerolog field name:

```go
zerolog.ErrorFieldName = "err"
```

But ideally we'd like to plug in a way to convert Go errors into the correct error field. Unfortunately, there doesn't seem to be a way to do this centrally. The only way I can see is to wrap every error:

```go
log.Err(logginghelpers.WrapError(err)).Msg("Thing went dingdingding")
// ...

func WrapError(err error) zerolog.LogObjectMarshaler { ... }
```

But that's not so nice.

Is there a better way?

**Comment by rs** [comment]
What about setting `zerolog.ErrorMarshalFunc`?

**Comment by atombender** [comment]
Jeez, I wonder why I missed that, I thought I had already looked for this. I'll try it out. Thanks!
