### ISSUE TITLE
Duration's output

### ISSUE THREAD

**Issue by a641390597** [rs/zerolog#309]
run this
``` 
	log.Debug().TimeDiff("duration1", time.Now().Add(time.Millisecond*1200), time.Now()).Send()
	log.Debug().Dur("duration2", time.Duration(time.Millisecond*1200)).Send()
	log.Print(time.Duration(time.Millisecond * 1200))
	fmt.Println(time.Duration(time.Millisecond * 1200))
```
output
```
$ go run .
{"level":"debug","duration1":1200,"time":"2021-04-15T16:40:01+08:00"}
{"level":"debug","duration2":1200,"time":"2021-04-15T16:40:01+08:00"}
{"level":"debug","time":"2021-04-15T16:40:01+08:00","message":"1.2s"}
1.2s
```
Duration's output should  like xx h xx m xx s xx ms,eg line 3,4，But now it’s in a time-like format
Is my useage wrong?

**Comment by rs** [comment]
The default format is in milliseconds. You add 1200ms, it shows 1200. Did you expect something different?

**Comment by lammel** [comment]
Actually I expected the default stringification of "2m3.232s" to be shown.
So currently I acutally use `log.Info().Str("dur", dur.String())` for logging the duration, which is requires more typing.

As time also shows a stringified format I expected Dur() to do the same.
I can live with either solution.
