### ISSUE TITLE
Log viewer

### ISSUE THREAD

**Issue by GaikwadPratik** [rs/zerolog#316]
Hi,

First of all, awesome library. 

This is more of question than anything else. Do we have any viewer, like [bunyan](https://github.com/trentm/node-bunyan) to read logs from file in color if they are not being written to console or terminal? If not, how hard would it be to make this compatible with [bunyan](https://github.com/trentm/node-bunyan)?

**Comment by GaikwadPratik** [comment]
@rs ,

Any thoughts or suggestions?

**Comment by mitar** [comment]
Existing pretty-printing console functionality is already taking JSON as input before pretty-printing it. I think it would be easy to make an utility around that.

**Comment by themarolt** [comment]
Just learning go for the past few months and I used bunyan and their CLI piping before so I hope I can make this happen :)
