### ISSUE TITLE
Feature: customizd interface marshaler

### ISSUE THREAD

**Issue by povsister** [rs/zerolog#317]
Currently, when using `logger.Debug().Interface("request_body", reqBody).Msg("request sent")` to log the request detail with customized types, zerolog first assert if the "reqBody" is a `LogObjectMarshaler` or not, if not, it tries the std json marshaler to serialize the request body.

As you can see in the code snippet. It's hard coded to `json.Marshal`.
https://github.com/rs/zerolog/blob/3c3b4a354e411c2af7f7ac649696cc5a590f2381/internal/json/types.go#L363-L371

However, for performance and convenient, mostly we do not use the standard json package for json encode/decode now.
I hope zerolog could have a package level `InterfaceMarshaler` variable, and use it to marshal object when needed.
It has the same signature with `json.Marshal`, so everyone can replace the internal reflection based marshaler at runtime without forking zerolog.
```go
type InterfaceMarshaler func(obj interface{}) (data []byte, err error)
```

PS: I am using [jsoniter](https://github.com/json-iterator/go) and have registered many customized encoders/decoders for customized types. That's why I hope zerolog can benefit from jsoniter without additional works.

**Comment by rs** [comment]
Can you please send a PR?

**Comment by povsister** [comment]
> Can you please send a PR?

Sure. Please take a look. https://github.com/rs/zerolog/pull/318
