### ISSUE TITLE
SetGlobalLevel causes Panic when using log.Print

### ISSUE THREAD

**Issue by suusan2go** [rs/zerolog#319]
When I use SetGlobalLevel and set log level to Info, `log.Print("message")` start causing panic. I think this is happening from v1.22.0.

You can confirm this by running this code below. This doesn't happen when I use v1.21.0

```go
package main

import (
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

func main() {
	zerolog.SetGlobalLevel(zerolog.InfoLevel)
	log.Print("test")
}
```

```bash
$ go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x10c1889]

goroutine 1 [running]:
github.com/rs/zerolog.(*Event).CallerSkipFrame(...)
	/Users/suusan2go/go/pkg/mod/github.com/rs/zerolog@v1.22.0/event.go:693
github.com/rs/zerolog/log.Print(0xc000058f68, 0x1, 0x1)
	/Users/suusan2go/go/pkg/mod/github.com/rs/zerolog@v1.22.0/log/log.go:118 +0x49
main.main()
	/Users/suusan2go/src/github.com/
```

I'm not sure but it seems this commit is related. https://github.com/rs/zerolog/commit/4de2fcc128ac133a397907b4b9865863f94caadf

**Comment by povsister** [comment]
https://github.com/rs/zerolog/blob/ffbd37b8d75fc1407f70aab005c35f8e2d9ecd45/log.go#L419-L423

`log.Print` uses `debug` level which belows `info`, so `newEvent` returns a nil `Event`.
Absolutely, a nil pointer dereference will be triggered here.

https://github.com/rs/zerolog/blob/ffbd37b8d75fc1407f70aab005c35f8e2d9ecd45/event.go#L700-L703

**Comment by ryanc414** [comment]
When will this be released? Not a great look for people like me who are interested in trying the project and it immediately panics on the simple "hello world" demo 😅

**Comment by Zenithar** [comment]
Thank you ^^
