### ISSUE TITLE
What does "chaining API" mean? Any links to explanations and/or examples?

### ISSUE THREAD

**Issue by simonhf** [rs/zerolog#326]
Golang newbie question: The README file says:

> Zerolog's API is designed to provide both a great developer experience and stunning performance. Its unique chaining API allows zerolog to write JSON (or CBOR) log events by avoiding allocations and reflection.
> 
> Uber's zap library pioneered this approach. Zerolog is taking this concept to the next level with a simpler to use API and even better performance.

What does 'chaining API' mean and how does it avoid allocations and reflection? I followed the link to zap but it does not mention the word 'chain' or 'chaining'. Googling also didn't offer any obvious hits. More info greatly appreciated. Thanks!

[1] https://github.com/rs/zerolog

**Comment by rs** [comment]
It's when the type is returned by its methods so you can do `log.Info().Str(...).Int(…).Msg("…")`.
