### ISSUE TITLE
The ConsoleWriter doesn't work well  on windows10 

### ISSUE THREAD

**Issue by Alecyrus** [rs/zerolog#33]
The Code:

![image](https://user-images.githubusercontent.com/13865581/35478626-402423ea-041d-11e8-8701-9b3778023e05.png)

The messy output in Windows 10 (git bash & powershell & cmd):
![image](https://user-images.githubusercontent.com/13865581/35478629-5c29e192-041d-11e8-94b4-3b4380b859ed.png)

And it‘s normal in Linux。
![image](https://user-images.githubusercontent.com/13865581/35478654-fc04de7e-041d-11e8-9cd4-5e523c6863ad.png)

It seems like the spaces are not displayed properly...

**Comment by rs** [comment]
The problem seems to come from the coloring. I guess powershell does not know how to interpret the escape sequence.

**Comment by Alecyrus** [comment]
The problems still exists.
> The zerolog has been updated to the latest version
 
#### Git Bash
![tim 20180309155940](https://user-images.githubusercontent.com/13865581/37196852-5d0ef056-23b3-11e8-9c2a-60cae65cf8d3.png)

#### PowerShell
![tim 20180309160136](https://user-images.githubusercontent.com/13865581/37196864-6af67784-23b3-11e8-893a-2b123cffd267.png)

**Comment by rs** [comment]
I need some doc on how PowerShell handle color (escape codes etc.). I know nothing about Windows.

**Comment by Alecyrus** [comment]
These docs that may help.
[GDI Printer](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162843.aspx)
[Printing](https://msdn.microsoft.com/en-us/library/windows/desktop/ff686805.aspx)

**Comment by toravir** [comment]
It is purely a problem with vscode and terminal emulation - see https://github.com/Microsoft/vscode/issues/22616 - there are number of similar issues with php, perl, python .. 

I don't think there is anything to do with zerolog.

**Comment by rs** [comment]
Closing this. Please reopen if you think we can fix something at zerolog level.

**Comment by cup** [comment]
https://github.com/rs/zerolog/issues/153

**Comment by timestee** [comment]
> Closing this. Please reopen if you think we can fix something at zerolog level.

use this(https://github.com/microsoft/terminal) terminal on windows could solve the problem.

**Comment by mozey** [comment]
> The problem seems to come from the coloring. I guess powershell does not know how to interpret the escape sequence.

This is correct, that is the problem. Escape sequences for colors don't work in `cmd.exe`. 

My solution is to just disable colors on Windows
```
noColor := false
if runtime.GOOS == "windows" {
    noColor = true
}
log.Logger = log.Output(ConsoleWriter{
    NoColor: noColor,
    // ...
})
```

> I need some doc on how PowerShell handle color (escape codes etc.). I know nothing about Windows.

FYI, the [gotest](https://github.com/rakyll/gotest) project does output colors correctly in `cmd.exe`. So the solution for supporting colors on Windows is probably in there somewhere. I'll have a look if I'm going to be spending lots of time on Windows, but if I can help it, probably not.

**Comment by rs** [comment]
The solution is this package apparently: https://github.com/mattn/go-colorable
