### ISSUE TITLE
can the filepath cut down?

### ISSUE THREAD

**Issue by linsijia1002** [rs/zerolog#333]
code:
log.Logger = zerolog.New(os.Stdout).With().Caller().Timestamp().Logger()

output:
{"l":"info","caller":"E:/go/first_project/src/xxx.com/xxx/xxx/cp_task/task_manager.go:28","t":"2021-07-21T15:02:52+08:00","msg":"xxxx"}

But I think the file path is too long. Could you cut it a little shorter?
 eg: "cp_task/task_manager.go:28"

thanks!

**Comment by rs** [comment]
Use compile time options to reduce the file paths in your binary.

**Comment by linsijia1002** [comment]
i try:
go build -gcflags=-trimpath=$GOPATH -asmflags=-trimpath=$GOPATH

But it didn't work, still print the full path

**Comment by woodgear** [comment]
same question here.
