### ISSUE TITLE
Async logging

### ISSUE THREAD

**Issue by kishaningithub** [rs/zerolog#340]
Does zerolog support async logging?

**Comment by kishaningithub** [comment]
My use case is the one mentioned here

https://github.com/sirupsen/logrus/issues/725#issuecomment-543785620

**Comment by rs** [comment]
You can use a diode for that, see:

https://github.com/rs/zerolog#thread-safe-lock-free-non-blocking-writer

**Comment by kishaningithub** [comment]
I see diodes can loose data.. but say we want no data loss and want async behaviour what would be the alternate?

Why not use channels with a large/configurable size? That way, writes happen to channel from the calling goroutine and another goroutine reads data and sends it to the underlying writer

**Comment by rs** [comment]
You can setup the diode with large enough buffers. With channels, if you fill the buffer you will have either to block your sender or drop messages.
