### ISSUE TITLE
log.Ctx() should return global logger instead of disabledLogger

### ISSUE THREAD

**Issue by irl-segfault** [rs/zerolog#344]
`log.Ctx(ctx)` returns the associated logger if it's been registered in the `ctx` and returns `disabledLogger` otherwise.  I think it should instead return the global logger.

It doesn't totally make intuitive sense to me that if a logger has *not* been registered in a context, that we by default assume logging should be disabled.  My use case it to pass a sub-logger. If I miss a call to `sublogger.WithContext()` somewhere, I don't want logging to be erroneously disabled as a result.

**Comment by rs** [comment]
Already fixed by #343
