### ISSUE TITLE
all: add (*testing.B).ReportAllocs() to all benchmarks

### ISSUE THREAD

**Issue by odeke-em** [rs/zerolog#355]
It is useful to track allocations per operation for all benchmarks so that on every change, there can be tangible data.

## Continuous benchmarking
Given that zerolog is a widely used logger and highly critical aiming for high performance, we'd love to help  with hassle free benchmarking. At Orijtech, Inc, we've built a continuous benchmarking product "gobencher" which is available for on the Github marketplace. For example for the last change by @thockin, this is what the benchmarks look like per https://dashboard.github.orijtech.com/benchmark/36b8caed37374c8d80e708a8f4bd2db2
![Screen Shot 2021-09-06 at 2 34 44 AM](https://user-images.githubusercontent.com/4898263/132195394-e7c3b156-edd9-43b9-93fe-eb92bceae747.png)

**Comment by cuonglm** [comment]
@odeke-em We will add `-benchmem` when running benchmark by default shortly, so we don't have to manually add like this for future changes.

**Comment by odeke-em** [comment]
> @odeke-em We will add `-benchmem` when running benchmark by default shortly, so we don't have to manually add like this for future changes.

Awesome, thank you my colleague @cuonglm :-) After we commit that change, please comment and let folks know they are good! I shall close this issue then.

**Comment by cuonglm** [comment]
@odeke-em Changes were deployed now 🎉
