### ISSUE TITLE
Severity lost when sent to syslog

### ISSUE THREAD

**Issue by nstansby** [rs/zerolog#356]
I'm trying to get zerolog to send to log/syslog and ultimately to a log aggregator service (in my case, Papertrail, but I don't think it matters which service you're using).  Either I'm missing something on how to pass the severity level through properly, or I've found a bug.

Using the vanilla Go logger, everything works fine:

```
import (
	"log"
	"log/syslog"
	"os"
)

func main() {
	writer, err := syslog.Dial("udp", os.Getenv("PAPERTRAIL_HOST"), syslog.LOG_EMERG|syslog.LOG_KERN, "vanillaGolangLogging")
	if err != nil {
		log.Fatal("failed to dial syslog")
	}
	writer.Debug("This is a debug test")
	writer.Warning("This is a warning test")
	writer.Err("This is an info test")
}
```

Results in (note the color-coded severity flags on the far left):
![image](https://user-images.githubusercontent.com/12901625/132434422-8f7e06eb-85c0-428a-aecc-55064b5f056d.png)

But when I try to do the same thing using zerolog, everything is sent as `emergency`:

```
import (
	"log"
	"log/syslog"
	"os"

	"github.com/rs/zerolog"
)

var logger zerolog.Logger

func main() {
	writer, err := syslog.Dial("udp", os.Getenv("PAPERTRAIL_HOST"), syslog.LOG_EMERG|syslog.LOG_KERN, "zerolog")
	if err != nil {
		log.Fatal("failed to dial syslog")
	}
	logger = zerolog.New(writer)

	logger.Debug().Msg("zerolog: This is a debug test")
	logger.Warn().Msg("zerolog: This is a warning test")
	logger.Info().Msg("zerolog: This is an info test")
}
```

Results in:
![image](https://user-images.githubusercontent.com/12901625/132434601-318f3ff6-89c3-4120-aeda-c242d6b3b1be.png)

Obviously the `emrgcy` tag is due to my `syslog.LOG_EMERG` in the `syslog.Dial()` call (verified by changing it), but I used the same params in the vanilla logger example and it still transmits logs with appropriate severities.

Seems like a defect, or am I doing something wrong?

**Comment by rs** [comment]
Use the `zerolog.SyslogWriter`
