### ISSUE TITLE
MultiLevelWriter message within message?

### ISSUE THREAD

**Issue by fgsch** [rs/zerolog#376]
I'm getting strange results with the MultiLevelWriter logger.
For example in this case:

```
package main

import (
	"github.com/rs/zerolog"
	"os"
)

func main() {
	multi := zerolog.MultiLevelWriter(zerolog.Nop(), zerolog.New(os.Stdout))
	logger := zerolog.New(multi)
	logger.Info().Msg("Hello World!")
}
```

I get:

```
{"message":"{\"level\":\"info\",\"message\":\"Hello World!\"}"}
```

It looks like it's wrapping the log within a message. 
Am I doing something wrong or this is working as expected?

**Comment by rs** [comment]
Please search previous closed issues, this has been explained already.
