### ISSUE TITLE
What is the minimum version of Go supported?

### ISSUE THREAD

**Issue by atc0005** [rs/zerolog#382]
Hi,

Many thanks for this awesome library, I use it often and am a big fan.

I checked the README, but didn't see it listed there: what is the minimum version of Go supported by this library?

Thanks!

**Comment by euskadi31** [comment]
With Go module 1.15

**Comment by atc0005** [comment]
Hi @euskadi31, thanks for the reply.

I understood the `go 1.15` value to indicate what Go module features should be used, not what the minimum supported version of Go is. Am I mistaken?

**Comment by euskadi31** [comment]
Hi @atc0005 

See: https://github.com/golang/go/issues/30446 and https://go-review.googlesource.com/c/go/+/164318/

**Comment by atc0005** [comment]
Ah ok, I see. Thanks for taking the time to share those references.

It looks like some of the 1.11 series releases had a bug which prevented building code which was marked as using a newer Go version.

This is what I believe I was remembering:

> The go directive was originally intended to support backward incompatible changes to the Go language (see Go 2 transition). There have been no incompatible language changes since modules were introduced, but the go directive still affects use of new language features:
> 
> - For packages within the module, the compiler rejects use of language features introduced after the version specified by the go directive. For example, if a module has the directive go 1.12, its packages may not use numeric literals like 1_000_000, which were introduced in Go 1.13.
> - If an older Go version builds one of the module’s packages and encounters a compile error, the error notes that the module was written for a newer Go version. For example, suppose a module has go 1.13 and a package uses the numeric literal 1_000_000. If that package is built with Go 1.12, the compiler notes that the code is written for Go 1.13.

In particular, the second bullet point.

refs https://go.dev/doc/modules/gomod-ref

This seems to suggest that Go 1.15 is the version of Go that the module is declared intended for, but not explicitly *required* in order to successfully build. I'm guessing that's because the value is set to whatever version of Go generated the go.mod file and that may not necessarily reflect what language features were used when developing the module.

In the end I don't suppose it really matters. As you noted, the go.mod file is a declaration by the module author indicating what Go version is *intended* as the minimum supported release.

Considering this answered.
