### ISSUE TITLE
empty slices taken from variables

### ISSUE THREAD

**Issue by SirBarksALot** [rs/zerolog#399]
Something weird is going on with methods ending with 's'. They work okay until you use argument vals as a variable.
First line works properly, the second one doesn't - outputs empty []string slice

Code:
```
fmt.Printf("%v\n",subscriptions)
log.Debug().Strs("live subscriptions", subscriptions).Send()
```
Output:
```
[1c96bb1d-1064-4507-9e85-f0d2b7e03968]                                                                                                                                                
2022-01-22T23:49:34Z DBG  live subscriptions= 
```
Any ideas?

**Comment by gilcrest** [comment]
Hey @SirBarksALot - I tried to recreate your issue on the playground, but seems to work fine for me: https://go.dev/play/p/3K-WuSvImvS

Is it possible to give a longer example or modify the one I provided to try and recreate?

**Comment by SirBarksALot** [comment]
You are right, it works on the playground, I tried locally the same code copy pasted and it works too, however, eventhough there is not magic in my app, it doesn't work there :/ the types are the same (I confirmed it with reflect package if strong typed wasn't enough), the formatting is the same, it is only bigger code base. Below I attach the whole function (in my app it is embedded into other functions obviously, but the call itself looks the same)
https://go.dev/play/p/42FI-Uxo2A5
I think we can close this one out, as it is not recreatable without whole codebase I assume.
