### ISSUE TITLE
[Question] Single Timestamp() without duplication

### ISSUE THREAD

**Issue by tyranron** [rs/zerolog#40]
Currently, if logger is configured with timestamps
```go
logger := zerolog.New(os.Stdout).With().Timestamp().Logger()
```

It will create a hook which fires on `Msg()` (an actual `time` field is generated and appended when `Msg()` is called).
```go
logger.Info().Str("body", "some").Msg("end")
// {"lvl":"info","body":"some","time":"2018-03-07T13:10:22.383313411Z","msg":"end"}
```

Sometimes we want to create a log message in one goroutine, but write in another. In this case we want to have timestamp when log entry is created, not when it's actually written. So we do something like:
```go
log := logger.Info().Timestamp().Str("body", "some")
go func() {
    // ...
    log.Msg("start")
}()
```
But `zerolog` duplicates timestamps in this case:
```go
// {"lvl":"info","time":"2018-03-07T13:17:11.177163291Z","body":"some","time":"2018-03-07T13:17:11.177194077Z","msg":"start"}
```

### Question

Is there a way to capture log entry timestamp early without timestamps duplication?

**Comment by rs** [comment]
No there is not, it’s part of the trick zerolog is doing to be super fast. It’s not a big deal though as JSON accepts dup keys, the last one prevails. It’s not clean though, I understand.

**Comment by tyranron** [comment]
@rs thank you for explanation.

I've ended up with using custom field to preserve required time.

I think, it will be OK no note possible duplication in Go docs of `Event.Timestamp()`. If you don't mind that, I will create a PR.

**Comment by rs** [comment]
Sure. That’s true with all fields though. If you repeat the same field several times it won’t get dedup’ed (which again is fine with JSON).
