### ISSUE TITLE
Question: can we force a compile error if Msg() or Send() is missing?

### ISSUE THREAD

**Issue by jlearman** [rs/zerolog#401]
Is there a way to force a compile error if we build a log event but forget to send it?

```
l := zerolog.New(os.Stdout)
l.Debug().Str("k", "v")

```
I've seen an error in a similar case (my errors package, which uses structured errors similar to Zerolog API.)  In that case, I didn't want the error because the functions had side effects that mattered.  Apparently the compiler can't see that in this case it's discarding a value without using it.

I want to avoid the case where someone thought they logged something but didn't, because they forgot `.Msg()` at the end.

**Comment by rs** [comment]
There is a linter in this package for this.

**Comment by jlearman** [comment]
I can't figure out how to use it.  It seems to expect my code to be in `$GOROOT/src/<pkg>`.
