### ISSUE TITLE
Using io.MultiWriter instead of Hooks

### ISSUE THREAD

**Issue by ykalayy** [rs/zerolog#404]
Hi everyone

Whenever writing data to remote(For example Fluentd or Logstash), Are there any big differences or side effects using io.MultiWriter instead of Hooks?

I mean

```
mw := io.MultiWriter(zerolog.ConsoleWriter{Out: os.Stdout}, myCustomIoWritter())
logger := zerolog.New(mw).With().Timestamp().Logger()
```

vs 

```
logger := zerolog.New(zerolog.ConsoleWriter{Out: os.Stdout}).With().Timestamp().Logger()
logger = logger:Hooks(myCustomHook())
```

**Comment by rs** [comment]
The hook does not have access to the JSON and is supposed to add fields. Another hook after your hook could add more fields.

**Comment by ykalayy** [comment]
https://github.com/halink0803/zerolog-graylog-hook

Oh, well. I saw this project using Hook to push logs to graylog(Confused me). And worried about my own io.MultiWriter solution as Is it a good choice to communicate with the remote side or hook is better?. 

But seems whenever I am working with Logstash JSON is pretty fine to me and there is no side effect of io.MultiWriter instead of Hook

Thanks for answer @rs

**Comment by rs** [comment]
This graylog plugin will only send the message, fields map will always be empty. It won’t work as expected.
