### ISSUE TITLE
Make it possible to exclude fields from console log

### ISSUE THREAD

**Issue by choover-broad** [rs/zerolog#411]
Hello! Thanks for all the great work on zerolog, it's been a pleasure to use.

We are using zerolog in a CLI tool with two writers, one to the console at info level and another to a file at debug level, using the solution described [here](https://github.com/rs/zerolog/issues/150#issuecomment-763603600).

We would like to add some additional context fields to all messages for debugging (for example, process id to distinguish between separate invocations of the tool), but don't want to include those fields in the console log because they add clutter.

I see there are already `PartsExclude` and `PartsOrder` options in the console logger for excluding some default fields. Would you be open to a PR for new options, `FieldsExclude` and `FieldsOrder`, that do the same thing but for contextual fields?

If there is a better way to accomplish what we are after, that works too!

**Comment by mitar** [comment]
Oh, I hoped that #411 also added `FieldsOrder`. It would be nice if we could customize which fields are prioritized and pulled to the front (with default being `error`).

**Comment by mitar** [comment]
This has been merged.
