### ISSUE TITLE
Public release and tagging

### ISSUE THREAD

**Issue by lvjp** [rs/zerolog#421]
When you go on the repository page, you can see that there is only one release : v1.0.0 on 23 June 2017

This can make think a lot of people that zerolog is an old and not very active project, but if we take a look we can really see how active is the project. Almost on tag per month !

It might be a good thing to automatically create release on tag with GitHub workflow

**Comment by yogi1990** [comment]
When is plan to merge this PR ?

**Comment by lvjp** [comment]
I close this issue, since the described needs are not enough for @rs…
