### ISSUE TITLE
panic: runtime error: index out of range [-1] seen when logging with many go coroutines running

### ISSUE THREAD

**Issue by aldickin** [rs/zerolog#422]
I have an application that is go routine heavy (need to do something, run it in a go routine is norm). When logging in this app, the following type of panic error is seen regularly:

```
panic: runtime error: index out of range [-1]

goroutine 27 [running]:
github.com/rs/zerolog/internal/json.Encoder.AppendKey(...)
	/okteto/golang/vendor/github.com/rs/zerolog/internal/json/base.go:15
github.com/rs/zerolog.(*Event).caller(0xc00061e360, 0x40eab4)
	/okteto/golang/vendor/github.com/rs/zerolog/event.go:744 +0x205
github.com/rs/zerolog.callerHook.Run({0xc000880000}, 0x473705, 0x78, {0x5628ef, 0xc00061e360})
	/okteto/golang/vendor/github.com/rs/zerolog/context.go:383 +0x32
github.com/rs/zerolog.(*Event).msg(0xc00061e360, {0xc0008c80e0, 0x64})
	/okteto/golang/vendor/github.com/rs/zerolog/event.go:134 +0x328
github.com/rs/zerolog.(*Event).Msgf(0xc00061e360, {0x1722d48, 0x0}, {0xc0005f3f68, 0x0, 0x0})
	/okteto/golang/vendor/github.com/rs/zerolog/event.go:129 +0x4e
golang/pkg/controllers/vtkendpoints.Controller.workLoop({0xc000127ee0, 0xc000028e70, 0xc000048ae0, 0xc000048c00, 0xc000048cc0, 0xc000125950, 0xc00057ccf0, 0xc000028ec0})
	/okteto/golang/pkg/controllers/vtkendpoints/controller.go:163 +0x15e
created by golang/pkg/controllers/vtkendpoints.Controller.Start
	/okteto/golang/pkg/controllers/vtkendpoints/controller.go:155 +0xf9 
```

The offending line is:
```
	if dst[len(dst)-1] != '{' {
```

In my debugger, a conditional breakpoint was added to break when `len(dst) == 0`.  The following frame in goroutine 84, shows that dst[] is empty:
![Screen Shot 2022-03-11 at 9 25 52 AM](https://user-images.githubusercontent.com/98416540/157947393-2d173f49-6f7a-4b73-8a2f-a7a36aa5e422.png)

The parent frame shows that the event's `buf` is `'{'`, which is inconsistent with the other frame:
![Screen Shot 2022-03-11 at 9 26 20 AM](https://user-images.githubusercontent.com/98416540/157947899-029b4ffd-d315-4ada-9213-4b021c6e2663.png)

The event at 0xc00059c000a was also seen in use in goroutine 2211. This goroutine would have appended `'{'` to the event buffer, which explains the difference between the above frames:
![Screen Shot 2022-03-11 at 9 43 35 AM](https://user-images.githubusercontent.com/98416540/157948780-fcbd502a-407c-48e5-910b-a512a844a787.png)

I guess that there is a problem with the event pooling when many go routines are run. The same event should not be made available to different simultaneous invocations.

**Comment by rs** [comment]
You are probably sharing the same logger event between goroutines.

**Comment by aldickin** [comment]
I am using the global logger for all of the log calls. Each call is made with the following semantics:
```
import (
	"github.com/rs/zerolog/log"
)

func main() {
    go func() {
        log.Info().Msg("hello from 1")
    }()
    go func() {
        log.Info().Msg("hello from 2")
    }()
}
```

Is there a different way that I should be logging?

**Comment by rs** [comment]
If you are able to reproduce the issue with such code, there is a bug. My guess is that you are doing something like:

```
    e :=  log.Info()
    go func() {
        e.Msg("hello from 1")
    }()
    go func() {
        e.Msg("hello from 2")
    }()

```

**Comment by aldickin** [comment]
Thanks @rs. That was the issue. I had one place in the code where I was reusing an event between two calls. The place where this was done was in the coroutines that were reusing the same event.

Closing this issue as it was a PEBKAC issue.
