### ISSUE TITLE
passing nil time to stringer panics

### ISSUE THREAD

**Issue by nathanfranke** [rs/zerolog#426]
```go
package main

import (
	"os"
	"time"

	"github.com/rs/zerolog"
)

func main() {
	l := zerolog.New(os.Stderr)
	var t *time.Time = nil
	l.Error().Stringer("time", t).Msg("error") // panic
}
```

**Comment by rs** [comment]
This is expected.

**Comment by nathanfranke** [comment]
Should the documentation for `Stringer` be updated then?

```
Stringer adds the field key with val.String() (or null if val is nil) to the *Event context.
```

**Comment by nathanfranke** [comment]
Also, methods in libraries should not panic. [The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values.](https://go.dev/blog/defer-panic-and-recover)

**Comment by rs** [comment]
It does not use panic(), you are sending a nil pointer, this is a programming error.

**Comment by nathanfranke** [comment]
```
Stringer adds the field key with val.String() (or null if val is nil) to the *Event context.
```

**Comment by rs** [comment]
If you send `nil` it won’t panic but that’s not what you are doing. See https://glucn.medium.com/golang-an-interface-holding-a-nil-value-is-not-nil-bb151f472cc7 for more context.
