### ISSUE TITLE
Enable hooks to transform Msg

### ISSUE THREAD

**Issue by worrel** [rs/zerolog#43]
Would it be possible to allow hooks to modify the message?

The use case I'm looking at is adding support for automatic redaction of potentially sensitive info (e.g. passwords, tokens) from log messages.  This wouldn't address devs intentionally logging this via a structured attribute, but that's fairly visible in code review.

**Comment by rs** [comment]
By message your mean the `message` field or the while line?

**Comment by worrel** [comment]
@rs just the message.  i realize it's not foolproof and devs can still leak sensitive stuff via Str(), Int() etc, but it's a start.

**Comment by aaronstaves** [comment]
@worrel I just stumbled across this. I am also am looking to mutate the message on log.  I've come up with this, but I'm not sure if this would be considered a "bad practice or not; specifically editing the "message" key on the logger.


```
// Create the hook:
type FilterSensitiveMsgDataHook struct{}

func (h FilterSensitiveMsgDataHook) Run(e *zerolog.Event, level zerolog.Level, msg string) {
	e.Str("message", filterSensitiveMsgData(msg))
}

func filterSensitiveMsgData(msg string) string {
	var filteredMsg string
	/* filter data in msg text */
	return filteredMsg
}

**Comment by tomakado** [comment]
The possibility to retrieve event's keys to sanitize values would be nice to have too.

**Comment by issmirnov** [comment]
@rs would you have any advice for us? Our company is facing a similar issue, and a middleware sanitizer would be ideal. If you have some pointers, our team can do some digging and share a solution once we discover one.

**Comment by dhduvall** [comment]
My workaround was to use a custom `MarshalZerologObject` for my type:

```golang
type Config struct {
    Username string
    Password string
}

func (c Config) MarshalZerologObject(e *zerolog.Event) {
	// Define a type identical to Config that isn't a LogObjectMarshaler to trick Event.Interface()
	type T Config
	var t T = (T)(c)

	t.Password = "REDACTED"

	e.Interface("config", t)
}
```
But this requires that you call `.EmbedObject()`. I couldn't think of a way to let the code at the log point to specify the key. In my case that's not a problem.

**Comment by shettyh** [comment]
Have a similar requirement to scrub PII data from event before logging, any useful solutions for this ?

**Comment by issmirnov** [comment]
@shettyh we solved it by adding a custom hook:

```go
// See https://github.com/rs/zerolog/pull/559/files
// and https://github.com/rs/zerolog#contextcontext-integration
type PiiHook struct{}

func (h PiiHook) Run(e *zerolog.Event, level zerolog.Level, msg string) {
	ctx := e.GetCtx()

	//  Implement me: massage 'msg' string and scrub PII patterns
}

```

When you construct the zerolog instance, register the hook:

```go
return zerolog.New(output).With().Timestamp().Logger().Hook(PiiHook{})
```

You'll need to adapt the logic of your hook, but this function will run on every logger call.

**Comment by shettyh** [comment]
Thanks @issmirnov for the quick response, but with the hook there is no way to look at all the keys already added to event right ?. Only message can be checked AFAIK, ideally i would like to look at all the key/values in event and also message

**Comment by issmirnov** [comment]
@shettyh you are correct, I misread your question.
