### ISSUE TITLE
how to disable log color ?

### ISSUE THREAD

**Issue by ChinaRedArmy1930** [rs/zerolog#431]
like this 
![image](https://user-images.githubusercontent.com/18543437/161184814-acbe3fc3-212f-40f7-8450-74bc3cf7916f.png)

**Comment by lookfirst** [comment]
```golang
log.Logger = log.Output(&zerolog.ConsoleWriter{Out: os.Stdout, NoColor: true})
```

**Comment by julien** [comment]
It would be nice if zerolog could support [NO_COLOR](https://no-color.org/)

**Comment by lookfirst** [comment]
`log.Logger = log.Output(&zerolog.ConsoleWriter{Out: os.Stdout, NoColor: os. Getenv("NO_COLOR")})`

**Comment by julien** [comment]
@lookfirst nice - thanks for the help.
