### ISSUE TITLE
Any time for a version release? :D

### ISSUE THREAD

**Issue by GalvinGao** [rs/zerolog#442]
Hi! Firstly, huge thanks for such a wonderful package! It's really easy to use with considering the nice API design of `rs/zerolog/log` which is simply a global singleton. Saves me tons of frustration.

I don't want to be acting like a pushy person but, I saw that several PRs are merged to the master (notably #406 and #409) but no new release/tag are created afterwards. Is there any chance for a release/tag around those times since those features are lovely additions to what zerolog currently have! I would be glad to provide any help if there needs any :D

**Comment by giovanism** [comment]
Seconded this. My project already has the todo to wait #409 all over places. 

```go
	// TODO: Use the updated sublogger passing via context when the following
	// patch is available. https://github.com/rs/zerolog/pull/409
	log := log.With().
		Str("event_type", ev.Context.GetType()).
		Str("event_id", ev.Context.GetID()).
		Str("event_source", ev.Context.GetSource()).
		Logger()
	ctx = (&log).WithContext(ctx)
```

Since I don't to be that guy that only +1, I'll throw another question. Is there any way the releases on https://pkg.go.dev/github.com/rs/zerolog?tab=versions can be synced with the one GitHub? Got me confused there.

**Comment by GalvinGao** [comment]
@giovanism The version listed on https://pkg.go.dev/github.com/rs/zerolog?tab=versions is in sync with the Git Tags, rather than GitHub Releases.

**Comment by rs** [comment]
I created a tag. Not sure of the value of creating gh release here.

**Comment by giovanism** [comment]
Yeah no worries about the releases not showing up here. Thanks for the release!

**Comment by GalvinGao** [comment]
Thanks for the release! Closing this issue as it has resolved

**Comment by GalvinGao** [comment]
Ummm I might've gone wrong but on https://github.com/rs/zerolog/tags it looks like the latest is still v1.27.0.

**Comment by GalvinGao** [comment]
> Ummm I might've gone wrong but on [rs/zerolog/tags](https://github.com/rs/zerolog/tags) it looks like the latest is still v1.27.0.



> Ummm I might've gone wrong but on [rs/zerolog/tags](https://github.com/rs/zerolog/tags) it looks like the latest is still v1.27.0.

cc @rs sorry for the ping but it looks like a tag is actually not been created?

**Comment by rs** [comment]
https://github.com/rs/zerolog/tree/v1.27.0
