### ISSUE TITLE
Deferring Zerolog output

### ISSUE THREAD

**Issue by akzincsystems** [rs/zerolog#444]
My Co. has standardised on Zerolog mainly because it's easy to use, writes JSON that can be ingested by Logstash  and gives a consistent interface.

We use it all our Go based systems, but I wanted to ask a question:

_When exactly does it write out the logs_?

In AWS Lambda based situations, I want to defer that until after the main (or handler) routine has returned. Is this default, or do I have to do some configuration, "code recipe" or some such?  Sorry, can't find much guidance in the docs or examples, unless I am missing something

BTW, we have developed a recipe that acts just like other language try:except blocks using Zerolog to capture and log the inevitable out of bounds failure.  Happy to share that if useful.

Kind regards
Ashley

**Comment by rs** [comment]
It writes on `Msg` or `Send`.

**Comment by akzincsystems** [comment]
So, it's sync in-line.  Is there a way of collecting the writes in a buffer to write them in one go at the end of a process?

**Comment by akzincsystems** [comment]
Or are you saying if I leave off Msg() or Send() and add it at some later stage, it will send all logs?  Surely that would just concatenate the entries?

**Comment by rs** [comment]
You can put a buffer on the `io.Writer` you give to zerolog.
