### ISSUE TITLE
long integer/int64 displayed as float

### ISSUE THREAD

**Issue by cheapRoc** [rs/zerolog#46]
I'm receiving the following log lines for a long integer/int64. It appears to be turned into a float.

```
2018-03-22T23:03:04-04:00 |DEBU| test log line thing_id=332962181439815681
2018-03-22T23:03:04-04:00 |DEBU| Query args=[3.332574358090875e+17] module=pgx rowCount=1 sql="\nSELECT id, name, created_at, updated_at\nFROM testtable\nWHERE id = $1 AND archived = false;\n"
```

The fields `thing_id` and `args` contain the same value `int64(332962181439815681)`. The first line formats the int64 properly by using `fmt.Sprintf("%d", thingID)` however just using the `Int64` field function in zerolog does not.

I've read somewhere that this is common due to the JSON parser/marshaling but I've yet to be able to reproduce a test case myself (except through zerolog).

Any thoughts would be great, unsure if this is a bug or what I'm doing wrong.

Thanks.

**Comment by rs** [comment]
Can you show the code that generates the second line?

**Comment by cheapRoc** [comment]
That particular line is being fed through zerolog via code [in this PR](https://github.com/jackc/pgx/pull/400/files#diff-1f86497a95267bd0a0d110c47e1d1796R38) so it's stemming from an `int64` value handled by `jackc/pgx`.

I'll have to spend some time reproducing the issue better. When I output an int64 manually using `Int64` everything works but this particular value is being converted somehow or isn't jiving with zerolog's handling of it. I was hoping someone had seen something similar in the past.

**Comment by rs** [comment]
Can you print `%#v` the `data` map please? This PR uses `interface{}` and not `Int64`. It should be mapped correctly though.

**Comment by cheapRoc** [comment]
Here's a proper example that reproduces the conditions using the log wrapper. I'm able to display the float that comes in by `.Fields(data)` as well as through `.Int64()` at the last call to log.

https://gist.github.com/cheapRoc/ffa69d3e5f0e5758fa8be75066ce0f42

The following is the output with Go-syntax values as you requested.

```
%#v map[args:[333543255570743297] time:2.678272ms rowCount:1 sql:SELECT id, name, apple_id FROM pears WHERE id = $1;]
2.678272 |INFO| Query args=[3.335432555707433e+17] module=pgx rowCount=1 sql="SELECT id, name, apple_id FROM pears WHERE id = $1;"
```

This definitely involves values stemming from the database driver as I'm able to log `int64` values otherwise.

**Comment by rs** [comment]
The int64 is a *int64 which is not supported yet in Fields. We can add pointers support for all types.

**Comment by cheapRoc** [comment]
👍 I didn't put two and two together on that one.

**Comment by cheapRoc** [comment]
Thank you so much @rs!!
