### ISSUE TITLE
Suggestion: add a way to disable warnings

### ISSUE THREAD

**Issue by Marcdsv** [rs/zerolog#480]
I am using zerolog for printing everything in my program, main information being at the InfoLevel.
Maybe I'm the only one in that case, but I would like to be able to add a cli option to disable warnings without disabling main information.

**Comment by pscheid92** [comment]
Hey @Marcdsv, could you provide more context to understand your use case?

For me, deactivating WARN or ERROR levels would be somewhat unintuitive. Those levels usually contain more critical information than the INFO level (also more important to a user). 🤔

**Comment by Marcdsv** [comment]
Hi! I agree on the convention, and also that deactivating the ERROR level would be unintuitive.

To give you more context on my case: my program receives messages, parses them to get some metrics/stats, and sends them elsewhere. I am using the INFO level as in the convention, for general information like service start/stop, progress status, total number of messages transferred... I always want to see this information.
When parsing messages (only for getting more detailed stats on the messages), if a message has unexpected/missing fields it will raise a WARNING, but it does not prevent the message from being transferred.
If there are a lot of messages with incorrect format, it will trigger many warnings and make the INFO log hard to find, in that case I would like to disable the WARNING level to only get the global stats printed at INFO level at the end of the program.

I hope it makes sense 😄

**Comment by pscheid92** [comment]
**I am 100% not sure if this is a good idea**, but I think I found a solution for you.

We can create a new logger with `zerolog.New(io.Writer)`. This function checks if the `io.Writer` implements the `LevelWriter` interface defined by zerolog. If the `io.Writer` doesn't, it wraps it into a thin wrapper. There I got the inspiration for a more or less hacky solution.

1. Implement your own `zerolog.LevelWriter`
2. Ignore all messages with level `zerolog.WarnLevel`
3. Replace your global logger

```go
package main

import (
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"io"
	"os"
)

func main() {
	writer := NoWarningLevelWriter{os.Stderr}
	log.Logger = zerolog.New(writer).With().Timestamp().Logger()

	log.Info().Msg("i am visible")
	log.Warn().Msg("i am invisible")
	log.Error().Msg("i am visible again")
}

type NoWarningLevelWriter struct {
	io.Writer
}

func (m NoWarningLevelWriter) WriteLevel(level zerolog.Level, p []byte) (n int, err error) {
	if level == zerolog.WarnLevel {
		return 0, nil
	}
	return m.Write(p)
}
```

Output:
```shell
$ go run . 

{"level":"info","time":"2022-10-12T12:10:59+02:00","message":"i am visible"}
{"level":"error","time":"2022-10-12T12:10:59+02:00","message":"i am visible again"}
```

**Comment by Marcdsv** [comment]
Well, as long as I'm the only one to request this feature (and it's not super important anyway) I'm totally ok with a hacky solution. Thanks!
