### ISSUE TITLE
Is it possible to select `Info` or `Error` level after log event is composed?

### ISSUE THREAD

**Issue by inliquid** [rs/zerolog#489]
I am new to `zerolog` and its api, so could you please help, in particular, is it possible to simplify this code:
```go
		if err != nil {
			log.Error().Str("delay", time.Since(t0).String()).
				Interface("args", req).
				Interface("result", resp).
				Err(err).
				Msg("Error calling service")
		} else {
			log.Info().Str("delay", time.Since(t0).String()).
				Interface("args", req).
				Interface("result", resp).
				Err(err).
				Msg("Service called")
		}
```
Can I for instance construct an event with all required fields and than push the message with correct level with `Msg` based on `err` value?

**Comment by inliquid** [comment]
Hey @pscheid92 !

Thank you for a detailed reply!

I found convenience sugar right in the api which does exact this:
```go
		log.Err(err).Str("delay", time.Since(t0).String()).
			Interface("args", req).
			Interface("result", resp).
			Err(err).
			Msg("Service called")
```

PS: I'm using `Str` instead of `Dur` because stringified duration is much better to read by humans.

**Comment by pscheid92** [comment]
OMG 🤯 I totally missed that! Thank you very much!

https://pkg.go.dev/github.com/rs/zerolog#Logger.Err
> Err starts a new message with error level with err as a field if not nil or with info level if err is nil.
