### ISSUE TITLE
Invalid condition in WithContext method.

### ISSUE THREAD

**Issue by tep** [rs/zerolog#498]
Since non-pointer receivers are passed **_by value_**, once the receiver for `WithContext` was reverted to a non-pointer, [this condition](https://github.com/rs/zerolog/blob/89617ff99b2feb29ab2d8b6258fac9d671073792/ctx.go#L30) is guaranteed to always be false.

In other words, the receiver (`l`) is a _copy_ of the Logger struct from the caller and its address can never be the same as the logger attached to the `Context`. 

Either the receiver should be converted back to a pointer (and different fixes devised for #116 and #400) -- or, this condition should simply be removed and the docs updated to say that the Context will always be replaced no matter what (because that's the actual behavior with the current logic).

[Here's a [Go Playground link](https://go.dev/play/p/Abw-heqUhwP) proving that non-pointer receivers have different addresses from those of their caller]

**Comment by rs** [comment]
This is a regression from this commit: https://github.com/rs/zerolog/commit/588a61c2df4bf7b92e12b826b226059b9f262190

**Comment by rs** [comment]
Perhaps we should remove the condition altogether.

**Comment by tep** [comment]
That's what I'd originally done in PR #499 but then changed it to add back a similar condition using `reflect.DeepEqual` but, I can always pull it out again.

**Comment by rs** [comment]
Ok, I'll prefer removing the condition then.

**Comment by tep** [comment]
Done. 

#499 should be ready to go.
