### ISSUE TITLE
Event.ctx to support OpenTelemetry

### ISSUE THREAD

**Issue by wcarmon** [rs/zerolog#501]
Is there an idiomatic way to access [context.Context](https://pkg.go.dev/context) from an [Event](https://github.com/rs/zerolog/blob/master/event.go#L22)?

My goal is to support [OpenTelemetry](https://opentelemetry.io/docs/)'s [`span.AddEvent(...)`](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/span.go#L465) seamlessly

(eg. if a `span` is in `ctx`, `log.Info().Msg("foo")` should invoke `span.AddEvent(...)`)

**Comment by danielbprice** [comment]
Hi @wcarmon, I worked on adding support for getting the context into the Event.  I believe that #559 has resolved this.  The caveat is that you will have to pass the ctx in: log.Info().Ctx(ctx).Msg("foo"), and you will need to write a Hook which does this and add it to your logger.
