### ISSUE TITLE
Upper Case Log Levels

### ISSUE THREAD

**Issue by mvrahden** [rs/zerolog#522]
The following commit introduced a bug for parsing log levels.

Please see my comment: https://github.com/rs/zerolog/commit/3543e9d94bc5ed088dd2d9ad1d19c7ccd0fa65f5#commitcomment-100418502

## Proposed Solution

~~My suggestion is to revert the `ParseLevel` function to what it was before and instead introduce a `ParseLevelEqualFold` or `ParseLevelCaseInsensitive` or similar to the code base~~

I'd suggest to lower case all the switch cases as well. Which will allow users to have the intended behaviour by one single function.

**Comment by mvrahden** [comment]
Please find the PR here: https://github.com/rs/zerolog/pull/523

**Comment by mitar** [comment]
#523 has been merged, I think this can be closed now.
