### ISSUE TITLE
Is it possible to log to FATAL with custom error code?

### ISSUE THREAD

**Issue by inliquid** [rs/zerolog#536]
In our cli tool we would like to have a custom error codes depending on some internal reason. However in `zerolog` `log.Fatal` is always implicitly calls `os.Exit(1)`, so it looks like it should be avoided. 

Is it possible to still have FATAL log level but with custom error codes?

**Comment by rs** [comment]
Use `Level` instead.

**Comment by inliquid** [comment]
Thank you, should we use `Level` only or `WithLevel` also suitable?
