### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by 982945902** [rs/zerolog#540]
this is my panic stack:
`
github.com/rs/zerolog/internal/json.Encoder.AppendKey(...)
	/go/src/jasmine/vendor/github.com/rs/zerolog/internal/json/base.go:15
github.com/rs/zerolog.(*Event).Timestamp(0x47fdfe?)
	/go/src/jasmine/vendor/github.com/rs/zerolog/event.go:651 +0x166
github.com/rs/zerolog.timestampHook.Run(...)
	/go/src/jasmine/vendor/github.com/rs/zerolog/context.go:327
github.com/rs/zerolog.(*Event).msg(0xc000986540, {0xc000316020, 0x1a})
	/go/src/jasmine/vendor/github.com/rs/zerolog/event.go:141 +0x8f
github.com/rs/zerolog.(*Event).Msgf(0xc000986540, {0xb4b1bf?, 0x40d947?}, {0xc000508280?, 0xa4e060?, 0x1?})
	/go/src/jasmine/vendor/github.com/rs/zerolog/event.go:129 +0x4e
coding.jd.com/mpc/go-common/trace.NewTimeLostRecorder({0xb53365, 0x14}, 0xc000508270)
	/go/src/jasmine/vendor/coding.jd.com/mpc/go-common/trace/record.go:23 +0x9f
main.(*BeaverServer).GetMatrixTripleUnary(0xc000306840, {0xc00070c4b0?, 0x4addc6?}, 0xc00070c4b0)
`

this is my code:

type (
	tlRecord struct {
		t time.Time
		v string
	}
	TimeLostRecorder struct {
		name    string
		logger  func(format string, v ...interface{})
		records []*tlRecord
		buffer  *bytes.Buffer
	}
)

func NewTimeLostRecorder(name string, logger func(format string, v ...interface{})) *TimeLostRecorder {
	logger("%s Start", name)
	return &TimeLostRecorder{
		buffer:  bytes.NewBuffer([]byte{}),
		name:    name,
		logger:  logger,
		records: []*tlRecord{&tlRecord{t: time.Now()}},
	}
}

func (timeLostRecorder *TimeLostRecorder) AddRecord(v string) *TimeLostRecorder {
	timeLostRecorder.records = append(timeLostRecorder.records, &tlRecord{t: time.Now(), v: v})
	return timeLostRecorder
}

func (timeLostRecorder *TimeLostRecorder) Commit() {
	fmt.Fprintf(timeLostRecorder.buffer, "%s Finish Cost %dms [", timeLostRecorder.name, timeLostRecorder.records[len(timeLostRecorder.records)-1].t.Sub(timeLostRecorder.records[0].t).Milliseconds())

	for i := 1; i < len(timeLostRecorder.records); i++ {
		fmt.Fprintf(timeLostRecorder.buffer, "%s Cost %dms,", timeLostRecorder.records[i].v, timeLostRecorder.records[i].t.Sub(timeLostRecorder.records[i-1].t).Milliseconds())
	}

	fmt.Fprintf(timeLostRecorder.buffer, "]")

	timeLostRecorder.logger("%s", timeLostRecorder.buffer.String())
}

func imploy() {
	s.lock.RLock()
	defer s.lock.RUnlock()
 
        trc := trace.NewTimeLostRecorder("GetMatrixTripleUnary", logger.Info().Msgf) //logger is a global zerolog.Logger
	defer trc.Commit()

        trc.AddRecord("acquire resource")
        trc.AddRecord("genMatrixTriple")
}

**Comment by I7yzan** [comment]
I have this problem too.

**Comment by 982945902** [comment]
> I have this problem too.

are you solved?

**Comment by I7yzan** [comment]
maybe this will help

https://github.com/rs/zerolog/issues/443
