### ISSUE TITLE
panic: runtime error: slice bounds out of range [128230:128000]

### ISSUE THREAD

**Issue by hariszukanovic** [rs/zerolog#545]
zerolog seems to exceed the given buffer size, regardless of the size I use.
it works for some time (sometimes even for 1 hour) and then randomly it overflows. I started with 4k arrived at 128k but getting the same exception. The frequency with which it happens seems to depend on the number of coroutines in use...

this is my init code, zerolog is a global var

var Console zerolog.Logger
AccessLogBufferSize = 128000

        // Init access log
        os.MkdirAll(path.Dir(AccessLogFileName), 0775)
        access_log_file, err := os.OpenFile(
                AccessLogFileName,
                os.O_APPEND|os.O_CREATE|os.O_WRONLY,
                0664,
        )
        if err != nil {
                Console.Fatal().Err(err).Msgf("Unable to open access log file: %s", AccessLogFileName)
        }
        w := bufio.NewWriter(access_log_file)
        Access = zerolog.New(bufio.NewWriterSize(w, AccessLogBufferSize)).With().Timestamp().Logger()

**Comment by rs** [comment]
bufio is not thread safe, that’s probably why. Any reason why you need a buffer here?

**Comment by hariszukanovic** [comment]
Actually, I am not really sure that I need it.
I found this example somewhere, trying to implement the idea to buffer log lines as to avoid writing them to disk one by one to avoid excessive disk operations...
Perhaps there is another way of achieving the same with only zerolog... without using bufio?

**Comment by rs** [comment]
If you want to reduce writes, you need to synchronize the writes to your buffer.

**Comment by hariszukanovic** [comment]
Actually, I chose to use zerolog having read it was thread-safe requiring no external synchronisation.
I do understand that making it use bufio actually makes that an invalid assumption.
So, I would still like to avoid doing the synchronisation, but at the same time buffer writes avoiding to trap into the kernel for each log line. I do still hope I am not try something impossible :)
 
On a second look.. Might I be looking exactly for the diode writer?
I do think loosing some logs in abnormal situations might be acceptable for my usecase...
https://github.com/rs/zerolog#thread-safe-lock-free-non-blocking-writer

**Comment by rs** [comment]
Zerolog is thread safe, bufio is not. A diode would be a good way to add synchronization to bufio.

**Comment by hariszukanovic** [comment]
Thank you @rs
