### ISSUE TITLE
New functions for improved composability

### ISSUE THREAD

**Issue by pltr** [rs/zerolog#56]
As of right now, zerolog's interface is not very composable. If you have an object that can be serialized and you want to log it, it can be very awkward to achieve that. Consider the following:
```go
type Price struct {
    val uint64
    prec int
    unit Unit 
}

var price = Price{val: 6449, prec: 2, unit: currency.USD}
```
And suppose it can be serialized into something like `$64.49`. Now to achieve it right now you need something like (assuming we want to keep the number of allocations to 0):
```go
var buf = getBuffer()
price.PrintJSONValue(buf)
log.Warn().Bytes("price", buf.Bytes()).Msg("Price is too high")
freeBuffer(buf)
```
this is a handful and leaks the implementation details of both price and zerolog to a degree. It also does an unnecessary copy.
Of course all of this could be avoided if price and zerolog coud somehow share the byte buffer.
One of the ways would be simply allowing the user access to the `zerolog.Event`'s internal buffer.
Another would be an interface like (the actual names are arbitrary):
```go
type JSONAppendable interface {
     JSONAppendTo([]byte) []byte
}
func (p *Price) JSONAppendTo(src []byte) (dst []byte) {
   // just assumes it's always dollars for demonstration purposes
    dst = append(src, `"$`...)
    dst = p.appendWholePart(dst)
    dst = append(dst, '.')
    dst = p.appendFracPart(dst)
    dst = append(dst, '"')
    return
}
//....
log.Warn().JSONVal("price", &price).Msg("Price is too high")

```
That interface can be reused/composed with not just zerolog but really any other custom json serializer, avoid unnecessary copies and keep the user of the logging call happily unaware about any implementation details

**Comment by rs** [comment]
You have to be aware that this feature would not be portable to the binary serialization (cc @toravir). Other than that, I'm fine with the idea.

**Comment by pltr** [comment]
@rs it's probably not significantly different in that regard to RawJSON?

**Comment by rs** [comment]
Sure

**Comment by toravir** [comment]
@pltr - can't this be done using the LogObjectMarshaler() callback ?? imo, users should not be aware of the zerolog's internal buffer. RawJSON() api does not build the JSON piece by piece - so this is slightly different, but possible in cbor...

**Comment by pltr** [comment]
@toravir I'm not sure I follow. Given that price object above and the following call:
```go
log.Info().Str("foo", "bar").Object("price", &price).Msg("Price is too high")
``` 
Would it be possible, assuming Price implements LogObjectMarshaler to result in 
```json
{"l":"info", "foo": "bar", "price": "$64.49", "m":"Price is too high"}
``` 
?
It seems MarshalZerologObject receives `zerolog.Event` object as the argument and Event doesn't seem to contain any methods that would allow the user to directly print into the current value. And even if it did it would leak the details significantly more than a generic JSOM buffer interface.

`JSONAppendable` isn't actually aware of anything, it's not even zerolog specific, it just expects *a* byte buffer and returns a filled buffer and that's about it. The only expectation there really is that the data it fills the buffer with is supposed to be valid JSON value. Which means it's very generic in nature and can be used with any similar json serializer. Of course in the case of zerolog it also means it's going to be zero copy/zero allocation, but but it's an implementation detail, however important.

**Comment by toravir** [comment]
Oh.. i know what you mean - the Object() api will make it look like ..,"price":{"value":"$64.49"},..  - it is not a clean log as "price":"$64.49".

Thinking about it... agree about `JSONAppendable` - it just adds its data as json value to the provided byte slice.

**Comment by toravir** [comment]
@pltr This is not exactly what you are looking for - but comes really close - https://github.com/toravir/zerolog/commit/8916864be42f1be83af6d6bebdf8fa0df6111dd6
Lemme know what you think..
