### ISSUE TITLE
Deprecate linter in favor of https://github.com/ykadowak/zerologlint

### ISSUE THREAD

**Issue by mitar** [rs/zerolog#567]
I think it is confusing to have two linters which are doing the same thing. https://github.com/ykadowak/zerologlint is integrated with go vet or through golangci-lint and it can be run as command line. In general it seems maintained. I think maybe it would be useful to officially endorse it and deprecate this linter to make sure all collective efforts are put into one project.

(I am not affiliated with https://github.com/ykadowak/zerologlint. I just realized that when I run it through golangci-lint I am not using one here.)

**Comment by rs** [comment]
I wasn't aware of this. Sounds good, feel free to make a PR and add to the readme that it is now integrated in go vet.

**Comment by mitar** [comment]
I made https://github.com/rs/zerolog/pull/574. If I understood you correctly (we are still keeping the lint in the repository, just documenting that it is deprecated).

BTW, I found those tools by chance. They are not mentioned in the main README at all!
