### ISSUE TITLE
Add context function for any

### ISSUE THREAD

**Issue by yangcheng** [rs/zerolog#576]
similar to https://github.com/rs/zerolog/issues/514 
now here is `Any` in event, need a similar change in context, so `log.With()` can use any 

```
// before
log.With().Interface("params", p).Msg("charge request")

// after
log.With().Any("params", p).Msg("charge request")

```

**Comment by mitar** [comment]
Feel free to make a PR.

**Comment by shettyh** [comment]
Added PR here https://github.com/rs/zerolog/pull/580/files
