### ISSUE TITLE
Add golang 1.21 slog to Benchmarks section

### ISSUE THREAD

**Issue by sruehl** [rs/zerolog#577]
Now that golang 1.21 has been released with the all new [slog](https://pkg.go.dev/log/slog) it would be good to update the [Benchmarks section](https://github.com/rs/zerolog#benchmarks) to compare to the builtin golang structured logger.

**Comment by sruehl** [comment]
as a side note: The link to logbench seems to be dead.
![image](https://github.com/rs/zerolog/assets/1769155/41dde3f1-70ee-4270-8c1d-a733cc8afe32)
![image](https://github.com/rs/zerolog/assets/1769155/643cd738-ef53-4ec0-93ed-10035e58ec50)

**Comment by rs** [comment]
I fixed the URL, thanks for the heads up. You can send a PR to https://github.com/rs/logbench
