### ISSUE TITLE
hook for loki

### ISSUE THREAD

**Issue by thisismz** [rs/zerolog#601]
Could someone please advise on the best way to configure zerolog to send logs to loki? Any example config snippets would be greatly appreciated.
something like this
https://github.com/YuKitsune/lokirus

**Comment by dyaa** [comment]
Thanks @rs. It would be great to update the README file with a snippet working with Loki, wdyt?

**Comment by sebbbastien** [comment]
Does anyone have any idea how to send zerolog to loki?
