### ISSUE TITLE
Creating sublogger from global log does not propagate global level

### ISSUE THREAD

**Issue by wilsonehusin** [rs/zerolog#624]
Play: https://go.dev/play/p/uuTKVfAzWke

```go
zerolog.SetGlobalLevel(zerolog.InfoLevel)
log.Info().Int8("level", int8(zerolog.GlobalLevel())).Send() // 1 = INFO

sub := log.With().Bool("sub", true).Logger()
sub.Info().Int8("level", int8(sub.GetLevel())).Send() // -1 = TRACE
```

This took me by surprise and wondering if it was intentional? Happy to send the patch, but for now my workaround is to do:

```diff
- sub := log.With().Bool("sub", true).Logger()
+ sub := log.Level(zerolog.GlobalLevel()).With().Bool("sub", true).Logger()
```

**Comment by rs** [comment]
The default logger does not have the global level set either. A local level on a logger can be set to a higher level than the global level to further restrict what is logged with this particular logger.

**Comment by wilsonehusin** [comment]
Oh interesting! I see why that makes sense now. Thanks!
