### ISSUE TITLE
Publish a new tag/release each time something is merged to main

### ISSUE THREAD

**Issue by freak12techno** [rs/zerolog#646]
So far, the latest tag was published on September, and `go install` installs not the latest version.
For example, when I am trying to install prettylog (via `go install github.com/rs/zerolog/cmd/prettylog@latest`), it installs not the latest version actually, which doesn't have for example my fix (https://github.com/rs/zerolog/pull/644).
Would be handy to have a new tag/release published every time a new commit is pushed to main, for example within a CI action or so.

**Comment by rs** [comment]
Just tagged a release. I don't think tagging every commit make sense.
