### ISSUE TITLE
log rotate Q

### ISSUE THREAD

**Issue by toravir** [rs/zerolog#65]
@rs - do you know what methods do users use for log rotation ?? From my analysis there are two methods:
i. rename the current log file (say log.txt) to say log.txt.1, and signal the process to close and re-open log.txt and start writing to the new log.txt file.
ii. copy the current log file (log.txt to log.txt.1) and then truncate the log.txt to null file... 

If users (especially binary log) use method ii, then the writer may have written partial log message into log.txt just as it is copied over to log.txt.1. So, a single log message bytes could be split into two pieces and first half is in the old file and second half in the new file. If this happens, binary logger will not be able to detect this.

OTOH, if users use method i, then the file is closed and re-opened and there is almost no chance of this single log msg split across two log files.

I ask - so that we can first document this, while i look for a way to handle (if needed).

Thx

**Comment by rs** [comment]
The method i. is the one I would use.

An alternative is to leave this job to syslog and log to a dgram UNIX socket.

**Comment by toravir** [comment]
@chinchani - what method do you use for log-rotation ?

**Comment by toravir** [comment]
Closing. Method i is the recommended approach.
