### ISSUE TITLE
level, message are built-in keywords? Field keywords level or message are invalid

### ISSUE THREAD

**Issue by sishui** [rs/zerolog#674]
version: 1.33.0
l.Debug().Int("level", 100).Msg("this int level") // I think it should be output `this int level level=100`, but output `this int level`
l.Debug().Str("message", "test").Msg("ok") // I think it should be output `ok message=test`, but output `ok`

**Comment by rs** [comment]
You seem to be using the console writer, which interprets the level key as the log level.
