### ISSUE TITLE
Example to show setting decendent logger to independently from parent logging level?

### ISSUE THREAD

**Issue by etsangsplk** [rs/zerolog#68]
Uber zap is very unfriendly for this, would like to see yours.
Would like to see one that people will just integrate and not thinking too much, but focus on the real requirement of their project.

**Comment by rs** [comment]
Could you please be more specific?

**Comment by etsangsplk** [comment]
What I mean was Logger Hierarchy just like below:
https://logging.apache.org/log4j/2.0/manual/architecture.html
Descendants loggers created from ancestors logger will inherit settings, unless overwrite it for itself and all the descendants logger inherit from there on, while leaving ancestors settings unchanged.
For Uber Zap, I need to wrap core and copy some configs over, and lots of settings are not accessible. It is just too much work for type of work like that using Uber Zap

**Comment by rs** [comment]
Aren’t you describing the API of zerolog? Every method to change level, output, context, etc. return a copy of the logger.
