### ISSUE TITLE
How to use this package like a isolated dependency using interface?

### ISSUE THREAD

**Issue by anazcodes** [rs/zerolog#691]
My application is dependent on many external packages. For example Database Driver, Payment Gateway,  all of these are communicating via `interface{}` to avoid  thinking of future concerns. I am using **Zerolog** or the last 7 months, but I used it as direct dependency in my program as I have not found any better solution. 

Are there any better solution to do it without losing any advantages of it ?

**Comment by chuksgpfr** [comment]
Hi @anazibinurasheed  can you give an example of what you have now and what you are trying to achieve.

**Comment by anazcodes** [comment]
Hi @chuksgpfr thank you for being a participant. I would like to inform you that, I've figured out the way for that.

FYI:
 I was accessing a Zerolog instance in my codebase without having any Abstraction or any Wrappers around it, which made the project tightly coupled with Zerolog. 
Wanted a better solution to make it loosely coupled without losing the flexibility, so I can change the logger if I want in future without having much overhead .
