### ISSUE TITLE
Changing output of level to int?

### ISSUE THREAD

**Issue by FuzzOli87** [rs/zerolog#70]
Hello,

My fluentd cluster is having issues indexing via level due to most other services using integer for level rather than string.

What is the recommended way to override the type that level outputs?

**Comment by rs** [comment]
There is currently no way to change the format of the level field. There is no standard for level to integer conversion, so I would not recommend using integers for this.

Can't fluentd be configured to accept strings?

**Comment by FuzzOli87** [comment]
@rs It can, its just that other clients(node-bunyan) default to integers. So creating an index on it broke it. 

I'll probably end up just relabeling the "level" field to something else and create a new index out of that.

**Comment by rs** [comment]
That's probably the best solution.

**Comment by FuzzOli87** [comment]
Changed the "level" property to "logLevel" to prevent clashing with pre-existing "level" index.
