### ISSUE TITLE
suggest zerolog support multiple output like log file and stderr / stdout 

### ISSUE THREAD

**Issue by tsingson** [rs/zerolog#73]
FYI

suggest zerolog support multiple output like log file and stderr / stdout  for debug on development

**Comment by rs** [comment]
You can use an `io.MultiWriter` for that.

**Comment by tsingson** [comment]
done. 

thanks a lot.

**Comment by tsingson** [comment]
thanks a lot.
done. it's work.

**Comment by PlkMarudny** [comment]
But it would be nice to have a possibility to use ConsoleWriter on os.Stdout, while a log wiritten to a file could be Json.

**Comment by rs** [comment]
Use io.MultiWriter.

**Comment by Grazfather** [comment]
More concretely (for others who got her via google)

```python
multi := io.MultiWriter(zerolog.ConsoleWriter{Out: os.Stderr}, myWriter)
logger = zerolog.New(multi).Logger()
```
