### ISSUE TITLE
Document the best strategy to send logs to external services

### ISSUE THREAD

**Issue by z0mbie42** [rs/zerolog#83]
Hi,

Is it possible to add documentation for the best strategies to ship log to external services ? (like loggly...)

In logrus it's done using hooks but zerolog seems to use the `io.Writer` interface.

So what is the best practice to implement a writer that write to `stdout` and ship logs to an external service (eg: logz.io...) ?

I understand best practices recommend to print to stdout (https://12factor.net/logs) and let your process manager ship logs, but sometime it's not possible. 

Best regards,
Sylvain

**Comment by rs** [comment]
There are many ways to ship your logs. It is out of the scope of this project to describe them all. With a `io.Writer`, you have the freedom to write your logs in files, stdout, directly on network etc.
