### ISSUE TITLE
Proposal: A customizable ConsoleWriter output

### ISSUE THREAD

**Issue by karmi** [rs/zerolog#84]
Hello, I've recently used `zerolog` in a project, and I like it very much — many thanks!

One thing I wanted to change was the `ConsoleWriter` output: I wanted to format the output differently, I wanted to highlight field values, not field names, etc. So I wrote a custom implementation, looking like this (adapting the output from `zerolog`'s README):

![Screenshot](https://raw.githubusercontent.com/karmi/consolelog/master/screenshot.png)

I've realized that my needs are probably not unique (see https://github.com/rs/zerolog/issues/34), and that it would be nice to expose a customizable `ConsoleWriter`. Therefore, I've extracted what I did in the project into a library, available at https://github.com/karmi/consolelog, since I didn't want to just blindly send code your way.

My question is: is this something you would consider interesting to have in the `zerolog` library itself? If so, I can move the implementation into a patch and send a pull request.

**Comment by rs** [comment]
Yes, as long as it is backward compatible.

**Comment by rs** [comment]
...and does not add extra dependencies.

**Comment by karmi** [comment]
Hi, understood about dependencies, but can you be more specific about "backwards compatibility" — as far as I understand it, the output type is just `io.Writer`, ie. the contract is in the `Write()` method. Or is there any other concern?

**Comment by rs** [comment]
Just make sure that the current API of the ConsoleWriter still works. Seems like it should not be an issue with the way you pass configuration.
