### ISSUE TITLE
Accessing errors and fields in hooks

### ISSUE THREAD

**Issue by asdine** [rs/zerolog#93]
I'd like to send whatever is logged on Error level to Sentry, but the hooks API only gives me a write only event that doesn't allow me to access log fields.
Is there a way to do so?

**Comment by asdine** [comment]
For now, i'm using an `io.Pipe` and passing an `io.MultiWriter(os.Stderr, pw)` to zerolog, and using a `json.Decoder` so i can extract the json from the output and use the fields i need.
It works fine (probably not the fastest way though) but i'm wondering if there is a simpler way.

**Comment by rs** [comment]
zerolog doesn’t store the error in an intermediary form; errors are serialized on the fly for best performance. The only way to access the fields in the hooks is to deserialize. Check the journald writer for an example.

**Comment by asdine** [comment]
Yep, that's pretty much what i did. Thank you 👍

**Comment by Dragomir-Ivanov** [comment]
@asdine Can you post here an example of your implementation? I need exactly the same thing, and it is not immediately obvious how to do it. Thanks a lot!

**Comment by asdine** [comment]
@Dragomir-Ivanov Sure, here is a gist https://gist.github.com/asdine/f821abe6189a04250ae61b77a3048bd9

Hope that helps

**Comment by Dragomir-Ivanov** [comment]
Thanks a ton, mate :)
