### ISSUE TITLE
Question about Error and os.Stderr

### ISSUE THREAD

**Issue by ldelossa** [rs/zerolog#95]
Question here that may come down to more practice then technical but I'm curious. In my applications I still expect errors to go out to Stderr, but we create a logger with one FD. That FD is usually standout. Are you guys sending >= Error to Stderr when logging (I'm using containers to it is the correct thing in my arch to send logs directly to these FDs). If you guys are, do you create two loggers one with Stderr and one with Stdout? 

Thanks.

**Comment by rs** [comment]
It really depend of your production environment. In my case I log to a dgram UNIX socket in prod with syslog-ng on the other side setup as a log shipper. In dev mode I use stderr with the ConsoleWriter for convenience.

When using stdout/err you have to make sure that whatever is reading this FD is fast enough at reading it so it does not block your process. Or you’ll have to use something like the diode writer (it’s generally a good idea anyway).

**Comment by rs** [comment]
There is a diode writer provided with zerolog here https://github.com/rs/zerolog/tree/master/diode.

**Comment by ldelossa** [comment]
@rs fantastic. Thanks for the help!
